// <auto-generated />
using CcDirector.Gateway.Stats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CcDirector.Gateway.Stats.Data.Migrations
{
    [DbContext(typeof(GatewayStatsDbContext))]
    [Migration("20260730160415_InitialGatewayStats")]
    partial class InitialGatewayStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<bool>("IsVoice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_voice");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.HasKey("Id");

                    b.ToTable("agent_delta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentDrivenDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.HasKey("Id");

                    b.ToTable("agent_driven_delta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentDrivenHighwaterEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("agent_driven_highwater", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentIdentityEntity", b =>
                {
                    b.Property<long>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_display");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.HasKey("AgentId");

                    b.ToTable("agent_identity", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentSessionEntity", b =>
                {
                    b.Property<long>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("AgentId", "SessionId");

                    b.ToTable("agent_session", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentsSeededEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("agents_seeded", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.CheckoutIdentityEntity", b =>
                {
                    b.Property<long>("CheckoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("checkout_id");

                    b.Property<string>("CheckoutDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("checkout_display");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.HasKey("CheckoutId");

                    b.ToTable("checkout_identity", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.MetaEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Tenant", "Name");

                    b.ToTable("meta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.ModelIdentityEntity", b =>
                {
                    b.Property<long>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<string>("ModelDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_display");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.HasKey("ModelId");

                    b.ToTable("model_identity", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.RepoIdentityEntity", b =>
                {
                    b.Property<long>("RepoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("repo_id");

                    b.Property<string>("RepoDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repo_display");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.HasKey("RepoId");

                    b.ToTable("repo_identity", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.RepoSessionEntity", b =>
                {
                    b.Property<long>("RepoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repo_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("RepoId", "SessionId");

                    b.ToTable("repo_session", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.SessionHighwaterEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Modality")
                        .HasColumnType("TEXT")
                        .HasColumnName("modality");

                    b.Property<string>("Surface")
                        .HasColumnType("TEXT")
                        .HasColumnName("surface");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.HasKey("Tenant", "SessionId", "Modality", "Surface");

                    b.ToTable("session_highwater", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.StatDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<long?>("CheckoutId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("checkout_id");

                    b.Property<string>("HourUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hour_utc");

                    b.Property<bool>("IsVoice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_voice");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("modality");

                    b.Property<long?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<long>("RepoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repo_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("surface");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.Property<bool>("Wingman")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wingman");

                    b.HasKey("Id");

                    b.HasIndex("HourUtc")
                        .HasDatabaseName("ix_stat_delta_hour");

                    b.HasIndex("Tenant", "HourUtc")
                        .HasDatabaseName("ix_stat_delta_tenant_hour");

                    b.ToTable("stat_delta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.TokenDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_read_tokens");

                    b.Property<string>("HourUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hour_utc");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<long?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.HasKey("Id");

                    b.HasIndex("HourUtc")
                        .HasDatabaseName("ix_token_delta_hour");

                    b.HasIndex("Tenant", "HourUtc")
                        .HasDatabaseName("ix_token_delta_tenant_hour");

                    b.ToTable("token_delta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.TokenHighwaterEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_read_tokens");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("token_highwater", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.WingmanSessionEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("wingman_session", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
