// <auto-generated />
using System;
using CcDirector.Gateway.Stats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CcDirector.Gateway.Stats.Data.Migrations
{
    [DbContext(typeof(GatewayStatsDbContext))]
    [Migration("20260731123456_HighwaterGenerationAndConcurrencyTables")]
    partial class HighwaterGenerationAndConcurrencyTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<bool>("IsVoice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_voice");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("tenant");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.HasKey("Id");

                    b.ToTable("agent_delta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentDrivenDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("tenant");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.HasKey("Id");

                    b.ToTable("agent_driven_delta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentDrivenHighwaterEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<long>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<long>("PreviousChars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_chars");

                    b.Property<long>("PreviousTurns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_turns");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("agent_driven_highwater", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentIdentityEntity", b =>
                {
                    b.Property<long>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_display");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("tenant");

                    b.HasKey("AgentId");

                    b.HasIndex("Tenant", "AgentDisplay")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_identity_tenant_display");

                    b.ToTable("agent_identity", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentSessionEntity", b =>
                {
                    b.Property<long>("AgentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("agent_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("AgentId", "SessionId");

                    b.ToTable("agent_session", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentsSeededEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("agents_seeded", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.CheckoutIdentityEntity", b =>
                {
                    b.Property<long>("CheckoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("checkout_id");

                    b.Property<string>("CheckoutDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("checkout_display");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("tenant");

                    b.HasKey("CheckoutId");

                    b.HasIndex("Tenant", "CheckoutDisplay")
                        .IsUnique()
                        .HasDatabaseName("ux_checkout_identity_tenant_display");

                    b.ToTable("checkout_identity", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.ConcurrencyHourEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("HourUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("hour_utc");

                    b.Property<int>("DistinctMachines")
                        .HasColumnType("INTEGER")
                        .HasColumnName("distinct_machines");

                    b.Property<int>("DistinctRepos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("distinct_repos");

                    b.Property<int>("DistinctSessions")
                        .HasColumnType("INTEGER")
                        .HasColumnName("distinct_sessions");

                    b.Property<int>("MaxLive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_live");

                    b.Property<int>("MaxWorking")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_working");

                    b.HasKey("Tenant", "HourUtc");

                    b.ToTable("concurrency_hour", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.ConcurrencyHourMemberEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("HourUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("hour_utc");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("MemberId")
                        .HasColumnType("TEXT")
                        .HasColumnName("member_id");

                    b.HasKey("Tenant", "HourUtc", "Kind", "MemberId");

                    b.ToTable("concurrency_hour_member", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.ConcurrencyPeakEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<int>("LiveMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("live_max");

                    b.Property<DateTime?>("LiveMaxAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("live_max_at_utc");

                    b.Property<int>("WorkingMax")
                        .HasColumnType("INTEGER")
                        .HasColumnName("working_max");

                    b.Property<DateTime?>("WorkingMaxAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("working_max_at_utc");

                    b.HasKey("Tenant");

                    b.ToTable("concurrency_peak", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.MetaEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Tenant", "Name");

                    b.ToTable("meta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.ModelIdentityEntity", b =>
                {
                    b.Property<long>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<string>("ModelDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_display");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("tenant");

                    b.HasKey("ModelId");

                    b.HasIndex("Tenant", "ModelDisplay")
                        .IsUnique()
                        .HasDatabaseName("ux_model_identity_tenant_display");

                    b.ToTable("model_identity", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.RepoIdentityEntity", b =>
                {
                    b.Property<long>("RepoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("repo_id");

                    b.Property<string>("RepoDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repo_display");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("tenant");

                    b.HasKey("RepoId");

                    b.HasIndex("Tenant", "RepoDisplay")
                        .IsUnique()
                        .HasDatabaseName("ux_repo_identity_tenant_display");

                    b.ToTable("repo_identity", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.RepoSessionEntity", b =>
                {
                    b.Property<long>("RepoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repo_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("RepoId", "SessionId");

                    b.ToTable("repo_session", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.SessionHighwaterEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Modality")
                        .HasColumnType("TEXT")
                        .HasColumnName("modality");

                    b.Property<string>("Surface")
                        .HasColumnType("TEXT")
                        .HasColumnName("surface");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<long>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<long>("PreviousChars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_chars");

                    b.Property<long>("PreviousTurns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_turns");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.HasKey("Tenant", "SessionId", "Modality", "Surface");

                    b.ToTable("session_highwater", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.StatDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Chars")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chars");

                    b.Property<long?>("CheckoutId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("checkout_id");

                    b.Property<string>("HourUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hour_utc");

                    b.Property<bool>("IsVoice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_voice");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("modality");

                    b.Property<long?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<long>("RepoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repo_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("surface");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("tenant");

                    b.Property<long>("Turns")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turns");

                    b.Property<bool>("Wingman")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wingman");

                    b.HasKey("Id");

                    b.HasIndex("HourUtc")
                        .HasDatabaseName("ix_stat_delta_hour");

                    b.HasIndex("Tenant", "HourUtc")
                        .HasDatabaseName("ix_stat_delta_tenant_hour");

                    b.ToTable("stat_delta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.TokenDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_read_tokens");

                    b.Property<string>("HourUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hour_utc");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<long?>("ModelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("model_id");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("local")
                        .HasColumnName("tenant");

                    b.HasKey("Id");

                    b.HasIndex("HourUtc")
                        .HasDatabaseName("ix_token_delta_hour");

                    b.HasIndex("Tenant", "HourUtc")
                        .HasDatabaseName("ix_token_delta_tenant_hour");

                    b.ToTable("token_delta", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.TokenHighwaterEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cache_read_tokens");

                    b.Property<long>("Generation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<long>("PreviousCacheCreationTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_cache_creation_tokens");

                    b.Property<long>("PreviousCacheReadTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_cache_read_tokens");

                    b.Property<long>("PreviousInputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_input_tokens");

                    b.Property<long>("PreviousOutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_output_tokens");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("token_highwater", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.WingmanSessionEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_id");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("wingman_session", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
