using CcDirector.Core.Security;
using Xunit;

namespace CcDirector.Core.Tests.Security;

/// <summary>
/// The credential rules, tested where they are decided rather than only through a live server.
///
/// The cross-language cases matter most. The command line derives its token in PYTHON
/// (tools/cc_shared/director_token.py) and the Director verifies it in C#, so the two
/// implementations have to agree byte for byte. Nothing else in either suite would notice if they
/// drifted: the C# tests would pass against the C# minting, the Python side has no server to talk
/// to, and the only symptom would be every command line call on every machine answered 401.
/// </summary>
public sealed class DirectorScopedTokenTests
{
    private const string Secret = "the-machine-secret";

    /// <summary>
    /// Pinned literals, generated by the PYTHON implementation and pasted here. That direction is
    /// deliberate: a value this test computed from the code it is testing would agree with itself
    /// forever. These agree with a different implementation in a different language, or they fail.
    /// </summary>
    [Theory]
    [InlineData(ScopeNames.Cli, null, "v1.cli..bb90uJEsFOMMSHAxvBx7VP1Ev5UKlG2nOFwY4Opib9w")]
    [InlineData(ScopeNames.Admin, null, "v1.admin..5RUdurdmGD5_jaXIBud_DeYKuUBsbI_wg1Ajy6DVFNg")]
    [InlineData(ScopeNames.SessionChild, "11111111-1111-1111-1111-111111111111",
        "v1.session-child.11111111-1111-1111-1111-111111111111.2-D4PpH-iMozeR6UpRlXExGKkUHuDj4NzimEZkH5w1g")]
    public void The_token_matches_the_command_lines_python_derivation(string scope, string? sessionId, string expected)
    {
        var minted = DirectorScopedToken.Mint(Secret, scope, sessionId is null ? null : Guid.Parse(sessionId));

        Assert.Equal(expected, minted);
        Assert.True(DirectorScopedToken.Verify(minted, Secret).IsValid);
    }

    [Fact]
    public void The_machine_secret_itself_is_full_authority()
    {
        var principal = DirectorScopedToken.Verify(Secret, Secret);

        Assert.True(principal.IsValid);
        Assert.Equal(ControlApiScope.Full, principal.Scope);
        Assert.Equal(ScopeNames.Root, principal.ScopeName);
    }

    [Theory]
    [InlineData(ScopeNames.Admin)]
    [InlineData(ScopeNames.Cli)]
    public void The_derived_full_scopes_are_full_authority_and_are_not_the_secret(string scope)
    {
        var token = DirectorScopedToken.Mint(Secret, scope);

        Assert.NotEqual(Secret, token);
        Assert.DoesNotContain(Secret, token, StringComparison.Ordinal);

        var principal = DirectorScopedToken.Verify(token, Secret);
        Assert.True(principal.IsValid);
        Assert.Equal(ControlApiScope.Full, principal.Scope);
        Assert.Null(principal.SessionId);
    }

    [Fact]
    public void A_child_token_carries_the_session_it_is_bound_to()
    {
        var sessionId = Guid.NewGuid();

        var principal = DirectorScopedToken.Verify(
            DirectorScopedToken.Mint(Secret, ScopeNames.SessionChild, sessionId), Secret);

        Assert.True(principal.IsValid);
        Assert.Equal(ControlApiScope.SessionChild, principal.Scope);
        Assert.Equal(sessionId, principal.SessionId);
    }

    /// <summary>
    /// The tamper cases. Each is a token that VERIFIED a moment ago, changed in exactly the way an
    /// attacker holding one would change it - raise the scope, re-point the binding, or present it
    /// to a Director that keeps a different secret.
    /// </summary>
    [Fact]
    public void Raising_the_scope_invalidates_the_token()
    {
        var child = DirectorScopedToken.Mint(Secret, ScopeNames.SessionChild, Guid.NewGuid());
        var raised = child.Replace(ScopeNames.SessionChild, ScopeNames.Admin);

        Assert.False(DirectorScopedToken.Verify(raised, Secret).IsValid);
    }

    [Fact]
    public void Repointing_the_binding_invalidates_the_token()
    {
        var a = Guid.NewGuid();
        var b = Guid.NewGuid();
        var token = DirectorScopedToken.Mint(Secret, ScopeNames.SessionChild, a);

        Assert.False(DirectorScopedToken.Verify(token.Replace(a.ToString(), b.ToString()), Secret).IsValid);
    }

    [Fact]
    public void A_token_from_another_machines_secret_is_refused()
    {
        var foreign = DirectorScopedToken.Mint("a-different-machines-secret", ScopeNames.Admin);

        Assert.False(DirectorScopedToken.Verify(foreign, Secret).IsValid);
    }

    /// <summary>
    /// A scope this build has never heard of is a refusal, not a guess. A deny-by-default here is
    /// what stops a future credential being silently promoted to whichever authority it resembles.
    /// </summary>
    [Fact]
    public void An_unknown_scope_is_refused_even_with_a_valid_signature()
    {
        var wellSigned = DirectorScopedToken.Mint(Secret, "supervisor");

        Assert.False(DirectorScopedToken.Verify(wellSigned, Secret).IsValid);
    }

    [Theory]
    [InlineData("")]
    [InlineData("not-a-token")]
    [InlineData("v1.admin.")]
    [InlineData("v2.admin..anything")]
    [InlineData("v1.admin.11111111-1111-1111-1111-111111111111.x")]
    public void Malformed_values_are_refused(string presented)
    {
        Assert.False(DirectorScopedToken.Verify(presented, Secret).IsValid);
    }

    /// <summary>A full-authority scope carrying a session binding is malformed, not a stronger
    /// child token - the two shapes must not blur into each other.</summary>
    [Fact]
    public void A_full_scope_bound_to_a_session_is_refused()
    {
        var sessionId = Guid.NewGuid();
        // Signed correctly for that material, so only the shape rule can refuse it.
        var child = DirectorScopedToken.Mint(Secret, ScopeNames.SessionChild, sessionId);
        var parts = child.Split('.');
        var confused = $"v1.{ScopeNames.Admin}.{parts[2]}.{parts[3]}";

        Assert.False(DirectorScopedToken.Verify(confused, Secret).IsValid);
    }

    [Fact]
    public void Minting_a_child_token_without_a_session_is_a_programming_error()
    {
        Assert.Throws<ArgumentException>(() => DirectorScopedToken.Mint(Secret, ScopeNames.SessionChild));
    }

    [Fact]
    public void Minting_a_full_scope_with_a_session_is_a_programming_error()
    {
        Assert.Throws<ArgumentException>(() => DirectorScopedToken.Mint(Secret, ScopeNames.Admin, Guid.NewGuid()));
    }
}
