namespace CcDirector.Core.Claude;

/// <summary>
/// Type of message displayed in the Simple Chat view.
/// </summary>
public enum ChatMessageType
{
    /// <summary>Message sent by the user.</summary>
    User,

    /// <summary>Completion summary from Claude (generated by Haiku after a turn finishes).</summary>
    Assistant,

    /// <summary>Periodic progress update while Claude is working (generated by Haiku).</summary>
    Status,

    /// <summary>Notification that Claude needs permission -- user should switch to Terminal tab.</summary>
    PermissionNotice
}

/// <summary>
/// A single message in the Simple Chat history. Immutable after creation.
/// </summary>
public sealed class ChatMessage
{
    public Guid Id { get; }
    public ChatMessageType Type { get; }
    public string Text { get; }
    public DateTimeOffset Timestamp { get; }

    public ChatMessage(ChatMessageType type, string text)
    {
        Id = Guid.NewGuid();
        Type = type;
        Text = text;
        Timestamp = DateTimeOffset.Now;
    }
}
