using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using CcDirector.Terminal.Core;
using Xunit;
using Xunit.Abstractions;
using static CcDirector.Core.Tests.TerminalTestHelper;

namespace CcDirector.Core.Tests;

/// <summary>
/// Replay a captured raw ANSI byte stream through our AnsiParser and assert the
/// resulting cell grid matches the ground-truth grid produced by @xterm/headless
/// (the same VT engine VS Code ships).
///
/// The expected *.expected.json fixtures are regenerated by running:
///   node tools/terminal-snapshot/snapshot-all.mjs
///
/// A failing test here means our parser has diverged from the industry-standard
/// xterm behavior for that input. Fix the parser, not the fixture.
/// </summary>
public class AnsiParserXtermSnapshotTests
{
    private readonly ITestOutputHelper _output;
    public AnsiParserXtermSnapshotTests(ITestOutputHelper output) => _output = output;

    [Fact]
    public void ClaudeStartup_MatchesXtermHeadless()
        => RunSnapshot("claude-startup", cols: 120, rows: 30);

    [Fact]
    public void ClaudeStrayChars_MatchesXtermHeadless()
        => RunSnapshot("claude-stray-chars", cols: 147, rows: 50);

    [Fact]
    public void ClaudeStrayToday_MatchesXtermHeadless()
        => RunSnapshot("claude-stray-today", cols: 147, rows: 47);

    [Fact]
    public void ClaudeSessionMedium_MatchesXtermHeadless()
        => RunSnapshot("claude-session-medium", cols: 147, rows: 50);

    [Fact]
    public void ClaudeSessionLarge47_MatchesXtermHeadless()
        => RunSnapshot("claude-session-large-47", cols: 147, rows: 47);

    [Fact]
    public void ClaudeSessionHuge50_MatchesXtermHeadless()
        => RunSnapshot("claude-session-huge-50", cols: 147, rows: 50);

    [Theory]
    [InlineData("claude-resize-gap",      147, 50)]
    [InlineData("claude-stray-chars",     147, 50)]
    [InlineData("claude-stray-today",     147, 47)]
    [InlineData("claude-session-medium",  147, 50)]
    [InlineData("claude-session-large-47",147, 47)]
    [InlineData("claude-session-huge-50", 147, 50)]
    public void DeferredAttachResize_AnyCapture_MatchesStaticGrid(string baseName, int finalCols, int finalRows)
    {
        var bytes = File.ReadAllBytes(LocateTestData(baseName + ".bin"));
        var expected = LoadExpected(LocateTestData(baseName + ".expected.json"));

        // Production deferred-attach: parser created at default 120x30,
        // then UpdateGrid is called when layout completes, then bytes arrive.
        var initialCells = new TerminalCell[120, 30];
        var scrollback = new List<TerminalCell[]>();
        var parser = new AnsiParser(initialCells, 120, 30, scrollback, 1000);

        var newCells = new TerminalCell[finalCols, finalRows];
        parser.UpdateGrid(newCells, finalCols, finalRows);
        parser.Parse(bytes);

        var diffs = Diff(expected, newCells, scrollback, finalCols, finalRows);
        AssertNoDiffs(diffs, $"deferred-attach[{baseName}]");
    }

    /// <summary>
    /// Torture test mirroring the production user-resize path:
    /// TerminalControl.HandleSizeChanged allocates a new cell grid, copies the
    /// overlapping region of the old grid into it, then calls UpdateGrid.
    /// The byte stream is delivered in random-sized chunks (1..256 bytes) and
    /// the resize fires at a random chunk boundary in the first 20% of the
    /// stream.
    ///
    /// Final state must equal the static-size xterm.js reference EXCEPT for
    /// scrollback rows that accumulated before the resize -- our parser does
    /// not reabsorb scrollback into the viewport on grow (xterm does). Those
    /// extra rows are tolerated; everything else (visible screen + cursor) is
    /// strict.
    ///
    /// Deterministic seeds so any failure is reproducible.
    /// </summary>
    [Theory]
    [InlineData("claude-resize-gap",      147, 50, 1)]
    [InlineData("claude-resize-gap",      147, 50, 7)]
    [InlineData("claude-resize-gap",      147, 50, 42)]
    [InlineData("claude-session-medium",  147, 50, 3)]
    [InlineData("claude-session-medium",  147, 50, 99)]
    [InlineData("claude-session-large-47",147, 47, 11)]
    [InlineData("claude-session-large-47",147, 47, 256)]
    [InlineData("claude-session-huge-50", 147, 50, 5)]
    [InlineData("claude-session-huge-50", 147, 50, 1234)]
    public void RandomChunkedParseWithMidStreamResize_ScreenMatchesStaticGrid(
        string baseName, int finalCols, int finalRows, int seed)
    {
        var bytes = File.ReadAllBytes(LocateTestData(baseName + ".bin"));
        var expected = LoadExpected(LocateTestData(baseName + ".expected.json"));

        const int initialCols = 120;
        const int initialRows = 30;
        var oldCells = new TerminalCell[initialCols, initialRows];
        var scrollback = new List<TerminalCell[]>();
        var parser = new AnsiParser(oldCells, initialCols, initialRows, scrollback, 1000);

        var rng = new Random(seed);
        int resizeAt = rng.Next(0, Math.Max(1, bytes.Length / 5));

        int pos = 0;
        while (pos < resizeAt)
        {
            int n = Math.Min(rng.Next(1, 257), resizeAt - pos);
            parser.Parse(bytes.AsSpan(pos, n).ToArray());
            pos += n;
        }

        // Mirror HandleSizeChanged: allocate new grid, copy overlap, swap.
        var newCells = new TerminalCell[finalCols, finalRows];
        int copyC = Math.Min(initialCols, finalCols);
        int copyR = Math.Min(initialRows, finalRows);
        for (int r = 0; r < copyR; r++)
            for (int c = 0; c < copyC; c++)
                newCells[c, r] = oldCells[c, r];
        parser.UpdateGrid(newCells, finalCols, finalRows);

        while (pos < bytes.Length)
        {
            int n = Math.Min(rng.Next(1, 257), bytes.Length - pos);
            parser.Parse(bytes.AsSpan(pos, n).ToArray());
            pos += n;
        }

        // Strict diff on the visible screen only. Scrollback comparison is
        // skipped because mid-stream resize cannot reproduce a "fresh terminal
        // at large size" scrollback exactly without a xterm-style reflow we
        // don't currently implement.
        var diffs = DiffScreenOnly(expected, newCells, finalCols, finalRows);
        AssertNoDiffs(diffs, $"chunked-resize-screen[{baseName}, seed={seed}, resizeAt={resizeAt}]");
    }

    /// <summary>
    /// Diff only the visible screen (no scrollback). Used by the chunked-resize
    /// torture test where pre-resize scrollback intentionally diverges.
    /// </summary>
    private static List<string> DiffScreenOnly(XtermSnapshot expected, TerminalCell[,] cells, int cols, int rows)
    {
        var diffs = new List<string>();
        var expectedScreen = expected.Screen ?? new List<XtermRow>();
        for (int r = 0; r < rows; r++)
        {
            if (r >= expectedScreen.Count) continue;
            var exp = expectedScreen[r];
            var row = new TerminalCell[cols];
            for (int c = 0; c < cols; c++) row[c] = cells[c, r];
            DiffRow(diffs, $"screen[{r}]", exp, row, cols);
            if (diffs.Count > 200) return diffs;
        }
        return diffs;
    }

    private void AssertNoDiffs(List<string> diffs, string label)
    {
        if (diffs.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine($"{diffs.Count} cell(s) diverge from @xterm/headless ({label}):");
        foreach (var d in diffs.Take(50))
            sb.AppendLine("  " + d);
        if (diffs.Count > 50) sb.AppendLine($"  ... and {diffs.Count - 50} more");

        _output.WriteLine(sb.ToString());
        Assert.Fail(sb.ToString());
    }

    /// <summary>
    /// Reproduces the production attach sequence that produced the
    /// "huge gap below the prompt" bug in Issue tracked 2026-04-22:
    ///
    ///   1. TerminalControl.Attach with Bounds == 0 creates the parser at
    ///      the default 120x30.
    ///   2. _pendingLayoutAttach defers byte parsing until layout completes.
    ///   3. Layout fires HandleSizeChanged -> UpdateGrid(147, 50).
    ///   4. Poll timer starts, the byte stream from Claude's redraw arrives
    ///      and is parsed at the new 147x50 dimensions.
    ///
    /// Before the UpdateGrid fix, _scrollBottom stayed clamped to 29 because
    /// the parser was constructed at 30 rows. Every linefeed past row 29
    /// scrolled within the stale region and dumped blank rows into scrollback,
    /// while rows 30-49 became a permanent dead band.
    ///
    /// xterm.js (the reference VT engine, opened directly at 147x50) produces
    /// 0 scrollback rows on this exact byte stream. Our parser must match.
    /// </summary>
    [Fact]
    public void ClaudeResizeGap_DeferredAttach_MatchesXtermHeadless()
    {
        var binPath = LocateTestData("claude-resize-gap.bin");
        var expectedPath = LocateTestData("claude-resize-gap.expected.json");

        var bytes = File.ReadAllBytes(binPath);

        // Step 1: parser created at deferred-attach default size (the bug
        // window). Scrollback list is shared with the parser by reference.
        var initialCells = new TerminalCell[120, 30];
        var scrollback = new List<TerminalCell[]>();
        var parser = new AnsiParser(initialCells, 120, 30, scrollback, 1000);

        // Step 3: layout completes, the cell grid is replaced and the parser
        // is told the new dimensions. This is exactly what
        // TerminalControl.HandleSizeChanged does.
        var newCells = new TerminalCell[147, 50];
        parser.UpdateGrid(newCells, 147, 50);

        // Step 4: bytes arrive from the post-resize Claude redraw.
        parser.Parse(bytes);

        var expected = LoadExpected(expectedPath);
        var diffs = Diff(expected, newCells, scrollback, cols: 147, rows: 50);

        if (diffs.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine($"{diffs.Count} cell(s) diverge from @xterm/headless after deferred-attach resize:");
        foreach (var d in diffs.Take(50))
            sb.AppendLine("  " + d);
        if (diffs.Count > 50) sb.AppendLine($"  ... and {diffs.Count - 50} more");

        _output.WriteLine(sb.ToString());
        Assert.Fail(sb.ToString());
    }

    private void RunSnapshot(string baseName, int cols, int rows)
    {
        var binPath = LocateTestData(baseName + ".bin");
        var expectedPath = LocateTestData(baseName + ".expected.json");

        var bytes = File.ReadAllBytes(binPath);
        var (parser, cells, scrollback) = CreateParser(cols, rows);
        parser.Parse(bytes);

        var expected = LoadExpected(expectedPath);
        var diffs = Diff(expected, cells, scrollback, cols, rows);

        if (diffs.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine($"{diffs.Count} cell(s) diverge from @xterm/headless ground truth for {baseName}:");
        foreach (var d in diffs.Take(50))
            sb.AppendLine("  " + d);
        if (diffs.Count > 50) sb.AppendLine($"  ... and {diffs.Count - 50} more");

        _output.WriteLine(sb.ToString());
        Assert.Fail(sb.ToString());
    }

    private static string LocateTestData(string filename)
    {
        var candidates = new[]
        {
            Path.Combine(AppContext.BaseDirectory, "TestData", filename),
            Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "TestData", filename),
            Path.Combine(Directory.GetCurrentDirectory(), "TestData", filename),
            Path.Combine(Directory.GetCurrentDirectory(), "..", "..", "..", "TestData", filename),
        };
        foreach (var c in candidates)
            if (File.Exists(c)) return Path.GetFullPath(c);
        throw new FileNotFoundException($"TestData file not found: {filename}");
    }

    private static XtermSnapshot LoadExpected(string path)
    {
        using var stream = File.OpenRead(path);
        var snap = JsonSerializer.Deserialize<XtermSnapshot>(
            stream,
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        return snap ?? throw new InvalidDataException($"Empty snapshot: {path}");
    }

    /// <summary>
    /// Compare our parser's grid against the xterm.js expected grid. Returns a
    /// list of human-readable diff lines (empty = identical).
    ///
    /// Comparison is character-first: we normalize unwritten cells ('\0') to
    /// space, and expected wide-char continuation cells (width=0) to space too,
    /// then compare the "visible" grapheme. Colors and attributes are compared
    /// separately in a later extension.
    /// </summary>
    private static List<string> Diff(XtermSnapshot expected, TerminalCell[,] cells,
        List<TerminalCell[]> scrollback, int cols, int rows)
    {
        var diffs = new List<string>();

        // Scrollback: xterm.js scrollback is all rows where y < viewportY.
        // Our scrollback is List<TerminalCell[]>, oldest at index 0.
        // The parser may have trimmed to maxScrollback; xterm.js also trims
        // to its scrollback setting. Both were configured to 1000.
        var expectedScrollback = expected.Scrollback ?? new List<XtermRow>();
        int expectedScrollbackCount = expectedScrollback.Count;
        int actualScrollbackCount = scrollback.Count;

        if (expectedScrollbackCount != actualScrollbackCount)
        {
            diffs.Add($"scrollback size: expected={expectedScrollbackCount} actual={actualScrollbackCount}");
        }

        // Align the newest N rows of each side so we can still diff even if
        // the counts differ (a common symptom of "scrolls too early/late" bugs).
        int n = Math.Min(expectedScrollbackCount, actualScrollbackCount);
        for (int i = 0; i < n; i++)
        {
            var exp = expectedScrollback[expectedScrollbackCount - n + i];
            var act = scrollback[actualScrollbackCount - n + i];
            DiffRow(diffs, $"scrollback[{actualScrollbackCount - n + i}]", exp, act, cols);
            if (diffs.Count > 200) return diffs;
        }

        // Screen.
        var expectedScreen = expected.Screen ?? new List<XtermRow>();
        for (int r = 0; r < rows; r++)
        {
            if (r >= expectedScreen.Count) continue;
            var exp = expectedScreen[r];
            // extract our row as array
            var row = new TerminalCell[cols];
            for (int c = 0; c < cols; c++) row[c] = cells[c, r];
            DiffRow(diffs, $"screen[{r}]", exp, row, cols);
            if (diffs.Count > 200) return diffs;
        }

        return diffs;
    }

    private static void DiffRow(List<string> diffs, string label, XtermRow expected, TerminalCell[] actual, int cols)
    {
        var expCells = expected.Cells;
        if (expCells is null) return;
        // Cap by both the expected count AND the actual array length. Scrollback
        // rows captured when the parser was at a narrower width are shorter than
        // the post-resize column count -- iterating to `cols` would index past
        // the end of the cell array.
        int end = Math.Min(Math.Min(cols, expCells.Count), actual.Length);
        for (int c = 0; c < end; c++)
        {
            var e = expCells[c];
            string expCh = NormalizeChar(e.Ch, e.W);
            string actCh = NormalizeChar(actual[c].Character);
            if (expCh != actCh)
            {
                diffs.Add($"{label} col {c,-3} char: expected='{Escape(expCh)}' actual='{Escape(actCh)}' (expW={e.W})");
                if (diffs.Count > 200) return;
            }
        }
    }

    private static string NormalizeChar(string? ch, int width)
    {
        // Width-0 cells are the continuation half of a wide character; xterm
        // stores these as empty string. For comparison, treat them as a space
        // so our (width-unaware) parser isn't penalized for writing the next
        // single-width char into that slot -- but wide-char rendering in our
        // own parser is still tracked by the width=2 case on the previous cell.
        if (width == 0) return " ";
        if (string.IsNullOrEmpty(ch)) return " ";
        return ch;
    }

    private static string NormalizeChar(char c)
    {
        if (c == '\0') return " ";
        return c.ToString();
    }

    private static string Escape(string s)
    {
        var sb = new StringBuilder();
        foreach (char c in s)
        {
            if (c < 0x20 || c == 0x7F) sb.Append($"\\x{(int)c:X2}");
            else sb.Append(c);
        }
        return sb.ToString();
    }

    // --- JSON DTOs matching the shape produced by tools/terminal-snapshot/snapshot.mjs ---

    private sealed class XtermSnapshot
    {
        [JsonPropertyName("meta")]       public XtermMeta? Meta { get; set; }
        [JsonPropertyName("cursor")]     public XtermCursor? Cursor { get; set; }
        [JsonPropertyName("dimensions")] public XtermDims? Dimensions { get; set; }
        [JsonPropertyName("scrollback")] public List<XtermRow>? Scrollback { get; set; }
        [JsonPropertyName("screen")]     public List<XtermRow>? Screen { get; set; }
    }

    private sealed class XtermMeta
    {
        [JsonPropertyName("source")] public string? Source { get; set; }
        [JsonPropertyName("bytes")]  public int Bytes { get; set; }
        [JsonPropertyName("cols")]   public int Cols { get; set; }
        [JsonPropertyName("rows")]   public int Rows { get; set; }
    }

    private sealed class XtermCursor
    {
        [JsonPropertyName("x")] public int X { get; set; }
        [JsonPropertyName("y")] public int Y { get; set; }
    }

    private sealed class XtermDims
    {
        [JsonPropertyName("cols")] public int Cols { get; set; }
        [JsonPropertyName("rows")] public int Rows { get; set; }
        [JsonPropertyName("totalBufferRows")] public int TotalBufferRows { get; set; }
        [JsonPropertyName("viewportY")]       public int ViewportY { get; set; }
    }

    private sealed class XtermRow
    {
        [JsonPropertyName("cells")]     public List<XtermCell>? Cells { get; set; }
        [JsonPropertyName("isWrapped")] public bool IsWrapped { get; set; }
    }

    private sealed class XtermCell
    {
        [JsonPropertyName("ch")]    public string? Ch { get; set; }
        [JsonPropertyName("w")]     public int W { get; set; } = 1;
        [JsonPropertyName("fg")]    public XtermColor? Fg { get; set; }
        [JsonPropertyName("bg")]    public XtermColor? Bg { get; set; }
        [JsonPropertyName("attrs")] public List<string>? Attrs { get; set; }
    }

    private sealed class XtermColor
    {
        [JsonPropertyName("mode")] public string? Mode { get; set; }
        [JsonPropertyName("r")]    public int R { get; set; }
        [JsonPropertyName("g")]    public int G { get; set; }
        [JsonPropertyName("b")]    public int B { get; set; }
        [JsonPropertyName("idx")]  public int Idx { get; set; }
    }
}
