using CcDirector.Core.Tenancy;
using CcDirector.Core.Utilities;
using CcDirector.Gateway.Data;
using CcDirector.Gateway.Data.Entities;
using CcDirector.Gateway.Tenancy;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Xunit;

namespace CcDirector.Gateway.Tests.Data;

/// <summary>
/// The hosted enrollment gate reads one table - <c>entitlements</c> - and a go-live outage traced to that
/// read resolving the relation through the connection's <c>search_path</c> instead of naming its schema.
/// These facts pin the gateway's OWN read path to an EXPLICIT schema so it can never depend on search_path
/// again, and they read that fact from EF's own SQL generation - not from a psql/psycopg2 re-derivation in
/// another client, which does not prove what THIS Gateway emits.
///
/// The qualification is a provider CONDITIONAL, not a fallback: Postgres names the <c>gateway</c> schema
/// (the table lives there), while SQLite is schemaless and takes no schema at all. So the property is proven
/// on EACH provider's OWN branch - Postgres asserts the schema-qualified SELECT, SQLite asserts the bare one
/// - because a Postgres-branch assertion evaluated on the SQLite model would pass for the wrong reason.
/// </summary>
public sealed class EntitlementSchemaQualificationTests
{
    private const string PgTestConnectionEnvVar = "CC_GATEWAY_TEST_PG_CONNECTION";

    /// <summary>A Fact that skips itself when the throwaway-Postgres connection is unset, so the normal
    /// SQLite test run and CI are unaffected. Anything reading a real PostgresException needs a real server.</summary>
    private sealed class RequiresPostgresFactAttribute : FactAttribute
    {
        public RequiresPostgresFactAttribute()
        {
            if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable(PgTestConnectionEnvVar)))
                Skip = $"Set {PgTestConnectionEnvVar} to a throwaway Postgres connection string to run the real-Postgres proof.";
        }
    }

    /// <summary>Build the model under the Npgsql provider WITHOUT opening a connection. ToQueryString and the
    /// entity's schema annotation come from EF's relational SQL generation for the selected provider, so this
    /// is the Postgres branch's real output - captured from EF itself, the Gateway's own read path.</summary>
    private static GatewayDbContext NpgsqlModel()
    {
        var options = new DbContextOptionsBuilder<GatewayDbContext>()
            .UseNpgsql("Host=localhost;Database=unused;Username=u;Password=p")
            .Options;
        return new GatewayDbContext(options) { ActiveTenant = TenantId.Local.Value };
    }

    private static GatewayDbContext SqliteModel()
    {
        var options = new DbContextOptionsBuilder<GatewayDbContext>()
            .UseSqlite("DataSource=:memory:")
            .Options;
        return new GatewayDbContext(options) { ActiveTenant = TenantId.Local.Value };
    }

    /// <summary>
    /// PROOF (b), Postgres branch. The entitlement read, generated by EF under the Npgsql provider, names the
    /// <c>gateway</c> schema: the SELECT is <c>FROM gateway.entitlements</c> and the entity's schema annotation
    /// is "gateway". This is the branch that ships to the hosted box.
    ///
    /// FAIL-ON-PURPOSE (verified during development): change the ToTable schema argument in
    /// <see cref="GatewayDbContext"/> back to an unqualified <c>ToTable("entitlements", ...)</c> AND remove the
    /// model-wide <c>HasDefaultSchema("gateway")</c>, and the FROM clause drops to a bare <c>entitlements</c>
    /// and this assertion reddens. (The explicit ToTable schema added here makes this one read gateway-qualified
    /// INDEPENDENTLY of the model-wide default, so removing the default alone no longer un-qualifies it.)
    /// </summary>
    [Fact]
    public void EntitlementRead_UnderPostgresProvider_GeneratesGatewaySchemaQualifiedSql()
    {
        using var ctx = NpgsqlModel();

        var entity = ctx.Model.FindEntityType(typeof(EntitlementEntity));
        Assert.NotNull(entity);
        Assert.Equal("gateway", entity!.GetSchema());
        Assert.Equal("entitlements", entity.GetTableName());

        var sql = ctx.Entitlements.AsNoTracking().Where(e => e.Subject == "any").ToQueryString();

        // The relation is schema-qualified. Postgres quotes an identifier only when it must, so EF emits the
        // bare-but-qualified form gateway.entitlements here; assert on that exact qualified reference.
        Assert.Contains("gateway.entitlements", sql);
        // And it is NOT the unqualified form that would resolve through search_path. The only occurrence of
        // "entitlements" as a FROM target must carry the schema, so there is no bare " entitlements" token
        // sitting where a relation reference goes.
        Assert.DoesNotContain("FROM entitlements", sql);
    }

    /// <summary>
    /// PROOF (b), SQLite branch (the self-host control at the model level). SQLite is schemaless, so the
    /// provider CONDITIONAL must emit NO schema: the entity carries no schema annotation and the SELECT names
    /// the bare table. This is what keeps self-host - which has no schemas - working unchanged, and it is why
    /// the schema argument is gated on the Postgres provider rather than applied unconditionally.
    /// </summary>
    [Fact]
    public void EntitlementRead_UnderSqliteProvider_GeneratesNoSchema()
    {
        using var ctx = SqliteModel();

        var entity = ctx.Model.FindEntityType(typeof(EntitlementEntity));
        Assert.NotNull(entity);
        Assert.Null(entity!.GetSchema());

        var sql = ctx.Entitlements.AsNoTracking().Where(e => e.Subject == "any").ToQueryString();
        Assert.DoesNotContain("gateway", sql);
        Assert.Contains("entitlements", sql);
    }

    /// <summary>
    /// PROOF (b), end-to-end on a REAL Postgres server. The gateway-schema-qualified read really resolves the
    /// entitlements table when that table exists in the <c>gateway</c> schema - so the qualification is not
    /// just in the generated string, it hits the right relation. The Gateway migrates the gateway schema but
    /// deliberately does NOT create entitlements (it is excluded from migrations and owned by the payment
    /// side), so the test creates it in the gateway schema exactly as the payment side would, then reads it
    /// through the Gateway's own <see cref="EntitlementRegistry"/>.
    /// </summary>
    [RequiresPostgresFact]
    public void EntitlementRead_AgainstRealPostgres_ResolvesGatewaySchemaTable()
    {
        var conn = Environment.GetEnvironmentVariable(PgTestConnectionEnvVar)!;
        var subject = "sub-live-" + Guid.NewGuid().ToString("N");
        var previous = Environment.GetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar);
        Environment.SetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar, conn);
        try
        {
            using var db = new GatewayDatabase(new SingleTenantContext());
            using (var ctx = db.CreateUnscopedContext())
            {
                // The payment side owns this table; create it in the gateway schema as that side would, and
                // seed one live, active entitlement. IF NOT EXISTS / delete-then-insert keeps the test rerunnable.
                ctx.Database.ExecuteSqlRaw(
                    "CREATE TABLE IF NOT EXISTS gateway.entitlements (" +
                    "subject text NOT NULL PRIMARY KEY, status text NOT NULL, " +
                    "current_period_end timestamptz NULL, stripe_subscription_id text NULL, " +
                    "updated_at timestamptz NULL, livemode boolean NULL);");
                ctx.Database.ExecuteSqlRaw("DELETE FROM gateway.entitlements WHERE subject = {0};", subject);
                ctx.Database.ExecuteSqlRaw(
                    "INSERT INTO gateway.entitlements (subject, status, livemode) VALUES ({0}, 'active', true);",
                    subject);
            }

            var registry = new EntitlementRegistry(db, requireLivemode: true);
            var outcome = registry.LookupBySubject(subject, DateTime.UtcNow);
            Assert.Equal(EntitlementOutcome.Entitled, outcome);
        }
        finally
        {
            Environment.SetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar, previous);
        }
    }

    /// <summary>
    /// PROOF (c). When the entitlement read fails with a <see cref="PostgresException"/>, the diagnostic log
    /// carries the two fields that actually pinpoint this class of outage - the SQLSTATE code and the server's
    /// message text - and NEVER the account subject. Driven through the Gateway's own read path against a real
    /// server: the Gateway migrates the gateway schema but not the entitlements table (excluded from
    /// migrations), so the qualified read throws SQLSTATE 42P01 (undefined_table) - a genuine PostgresException,
    /// not a constructed one.
    /// </summary>
    [RequiresPostgresFact]
    public void EntitlementReadFailure_OnPostgresException_LogsSqlStateAndMessageText_NeverSubject()
    {
        var conn = Environment.GetEnvironmentVariable(PgTestConnectionEnvVar)!;
        // A subject with a distinctive, PII-shaped marker so a leak into the log is unmistakable.
        var subject = "sub-PII-marker-" + Guid.NewGuid().ToString("N");
        var previous = Environment.GetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar);
        Environment.SetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar, conn);

        IReadOnlyList<string> lines;
        EntitlementOutcome outcome;
        try
        {
            using var db = new GatewayDatabase(new SingleTenantContext());

            // Make sure the entitlements table is ABSENT so the gateway-qualified read fails with 42P01.
            using (var ctx = db.CreateUnscopedContext())
                ctx.Database.ExecuteSqlRaw("DROP TABLE IF EXISTS gateway.entitlements;");

            var registry = new EntitlementRegistry(db, requireLivemode: true);

            using var scope = FileLog.RedirectForTests();
            outcome = registry.LookupBySubject(subject, DateTime.UtcNow);
            lines = scope.DrainAndReadLines();
        }
        finally
        {
            Environment.SetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar, previous);
        }

        // Ignorance, not absence: a failed read is Unknown, never a denial or a grant.
        Assert.Equal(EntitlementOutcome.Unknown, outcome);

        var diagnostic = Assert.Single(lines, l => l.Contains("PostgreSQL error"));
        Assert.Contains("SqlState=42P01", diagnostic);
        Assert.Contains("MessageText=", diagnostic);

        // The never-log-the-subject rule holds across EVERY line the read produced, not just the new one.
        Assert.DoesNotContain(lines, l => l.Contains(subject));
    }
}
