// <auto-generated />
using System;
using CcDirector.Gateway.Stats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CcDirector.Gateway.Migrations.Postgres.StatsMigrations
{
    [DbContext(typeof(GatewayStatsDbContext))]
    [Migration("20260801170503_TenantRequiredNoDefaultAndNonEmpty")]
    partial class TenantRequiredNoDefaultAndNonEmpty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gateway_stats")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<long>("Chars")
                        .HasColumnType("bigint")
                        .HasColumnName("chars");

                    b.Property<bool>("IsVoice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_voice");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<long>("Turns")
                        .HasColumnType("bigint")
                        .HasColumnName("turns");

                    b.HasKey("Id");

                    b.ToTable("agent_delta", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_agent_delta_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentDrivenDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<long>("Chars")
                        .HasColumnType("bigint")
                        .HasColumnName("chars");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<long>("Turns")
                        .HasColumnType("bigint")
                        .HasColumnName("turns");

                    b.HasKey("Id");

                    b.ToTable("agent_driven_delta", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_agent_driven_delta_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentDrivenHighwaterEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.Property<long>("Chars")
                        .HasColumnType("bigint")
                        .HasColumnName("chars");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<long>("PreviousChars")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_chars");

                    b.Property<long>("PreviousTurns")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_turns");

                    b.Property<long>("Turns")
                        .HasColumnType("bigint")
                        .HasColumnName("turns");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("agent_driven_highwater", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_agent_driven_highwater_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentIdentityEntity", b =>
                {
                    b.Property<long>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AgentId"));

                    b.Property<string>("AgentDisplay")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_display")
                        .UseCollation("C");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.HasKey("AgentId");

                    b.HasIndex("Tenant", "AgentDisplay")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_identity_tenant_display");

                    b.ToTable("agent_identity", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_agent_identity_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentSessionEntity", b =>
                {
                    b.Property<long>("AgentId")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.HasKey("AgentId", "SessionId");

                    b.ToTable("agent_session", "gateway_stats");
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.AgentsSeededEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("agents_seeded", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_agents_seeded_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.CheckoutIdentityEntity", b =>
                {
                    b.Property<long>("CheckoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("checkout_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CheckoutId"));

                    b.Property<string>("CheckoutDisplay")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checkout_display")
                        .UseCollation("C");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.HasKey("CheckoutId");

                    b.HasIndex("Tenant", "CheckoutDisplay")
                        .IsUnique()
                        .HasDatabaseName("ux_checkout_identity_tenant_display");

                    b.ToTable("checkout_identity", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_checkout_identity_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.ConcurrencyHourEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<string>("HourUtc")
                        .HasColumnType("text")
                        .HasColumnName("hour_utc")
                        .UseCollation("C");

                    b.Property<int>("DistinctMachines")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_machines");

                    b.Property<int>("DistinctRepos")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_repos");

                    b.Property<int>("DistinctSessions")
                        .HasColumnType("integer")
                        .HasColumnName("distinct_sessions");

                    b.Property<int>("MaxLive")
                        .HasColumnType("integer")
                        .HasColumnName("max_live");

                    b.Property<int>("MaxWorking")
                        .HasColumnType("integer")
                        .HasColumnName("max_working");

                    b.HasKey("Tenant", "HourUtc");

                    b.ToTable("concurrency_hour", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_ConcurrencyHours_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.ConcurrencyHourMemberEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<string>("HourUtc")
                        .HasColumnType("text")
                        .HasColumnName("hour_utc")
                        .UseCollation("C");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind")
                        .UseCollation("C");

                    b.Property<string>("MemberId")
                        .HasColumnType("text")
                        .HasColumnName("member_id")
                        .UseCollation("C");

                    b.HasKey("Tenant", "HourUtc", "Kind", "MemberId");

                    b.ToTable("concurrency_hour_member", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_ConcurrencyHourMembers_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.ConcurrencyPeakEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<int>("LiveMax")
                        .HasColumnType("integer")
                        .HasColumnName("live_max");

                    b.Property<DateTime?>("LiveMaxAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("live_max_at_utc");

                    b.Property<int>("WorkingMax")
                        .HasColumnType("integer")
                        .HasColumnName("working_max");

                    b.Property<DateTime?>("WorkingMaxAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("working_max_at_utc");

                    b.HasKey("Tenant");

                    b.ToTable("concurrency_peak", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_ConcurrencyPeaks_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.MetaEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .UseCollation("C");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value")
                        .UseCollation("C");

                    b.HasKey("Tenant", "Name");

                    b.ToTable("meta", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_meta_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.ModelIdentityEntity", b =>
                {
                    b.Property<long>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("model_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ModelId"));

                    b.Property<string>("ModelDisplay")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_display")
                        .UseCollation("C");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.HasKey("ModelId");

                    b.HasIndex("Tenant", "ModelDisplay")
                        .IsUnique()
                        .HasDatabaseName("ux_model_identity_tenant_display");

                    b.ToTable("model_identity", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_model_identity_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.RepoIdentityEntity", b =>
                {
                    b.Property<long>("RepoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("repo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RepoId"));

                    b.Property<string>("RepoDisplay")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repo_display")
                        .UseCollation("C");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.HasKey("RepoId");

                    b.HasIndex("Tenant", "RepoDisplay")
                        .IsUnique()
                        .HasDatabaseName("ux_repo_identity_tenant_display");

                    b.ToTable("repo_identity", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_repo_identity_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.RepoSessionEntity", b =>
                {
                    b.Property<long>("RepoId")
                        .HasColumnType("bigint")
                        .HasColumnName("repo_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.HasKey("RepoId", "SessionId");

                    b.ToTable("repo_session", "gateway_stats");
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.SessionHighwaterEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.Property<string>("Modality")
                        .HasColumnType("text")
                        .HasColumnName("modality")
                        .UseCollation("C");

                    b.Property<string>("Surface")
                        .HasColumnType("text")
                        .HasColumnName("surface")
                        .UseCollation("C");

                    b.Property<long>("Chars")
                        .HasColumnType("bigint")
                        .HasColumnName("chars");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<long>("PreviousChars")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_chars");

                    b.Property<long>("PreviousTurns")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_turns");

                    b.Property<long>("Turns")
                        .HasColumnType("bigint")
                        .HasColumnName("turns");

                    b.HasKey("Tenant", "SessionId", "Modality", "Surface");

                    b.ToTable("session_highwater", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_session_highwater_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.StatDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Chars")
                        .HasColumnType("bigint")
                        .HasColumnName("chars");

                    b.Property<long?>("CheckoutId")
                        .HasColumnType("bigint")
                        .HasColumnName("checkout_id");

                    b.Property<string>("HourUtc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hour_utc")
                        .UseCollation("C");

                    b.Property<bool>("IsVoice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_voice");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modality")
                        .UseCollation("C");

                    b.Property<long?>("ModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_id");

                    b.Property<long>("RepoId")
                        .HasColumnType("bigint")
                        .HasColumnName("repo_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surface")
                        .UseCollation("C");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<long>("Turns")
                        .HasColumnType("bigint")
                        .HasColumnName("turns");

                    b.Property<bool>("Wingman")
                        .HasColumnType("boolean")
                        .HasColumnName("wingman");

                    b.HasKey("Id");

                    b.HasIndex("HourUtc")
                        .HasDatabaseName("ix_stat_delta_hour");

                    b.HasIndex("Tenant", "HourUtc")
                        .HasDatabaseName("ix_stat_delta_tenant_hour");

                    b.ToTable("stat_delta", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_stat_delta_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.TokenDeltaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_tokens");

                    b.Property<string>("HourUtc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hour_utc")
                        .UseCollation("C");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<long?>("ModelId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_id");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.HasKey("Id");

                    b.HasIndex("HourUtc")
                        .HasDatabaseName("ix_token_delta_hour");

                    b.HasIndex("Tenant", "HourUtc")
                        .HasDatabaseName("ix_token_delta_tenant_hour");

                    b.ToTable("token_delta", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_token_delta_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.TokenHighwaterEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_creation_tokens");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("cache_read_tokens");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint")
                        .HasColumnName("generation");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<long>("PreviousCacheCreationTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_cache_creation_tokens");

                    b.Property<long>("PreviousCacheReadTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_cache_read_tokens");

                    b.Property<long>("PreviousInputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_input_tokens");

                    b.Property<long>("PreviousOutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_output_tokens");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("token_highwater", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_token_highwater_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Stats.Data.Entities.WingmanSessionEntity", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant")
                        .UseCollation("C");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id")
                        .UseCollation("C");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("wingman_session", "gateway_stats", t =>
                        {
                            t.HasCheckConstraint("ck_wingman_session_tenant_not_empty", "\"tenant\" <> ''");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
