// Typed Gateway reads for the session awareness surfaces (issue #974): the "what's happening" recap
// and the per-turn summaries. This is the TypeScript twin of the Cockpit's DirectorClient.GetRecapAsync
// / GenerateRecapAsync / GetTurnSummariesAsync (src/CcDirector.Cockpit/Services/DirectorClient.cs).
//
// Like the Brief and history reads, these endpoints are NOT declared in the Gateway's OpenAPI document
// - they ride the generic per-session catch-all proxy (/sessions/{sid}/{**rest}) with the injected
// Bearer - so they are read with narrow local shapes that mirror the C# DTOs
// (CcDirector.Gateway.Contracts.RecapResponse / TurnSummary / TurnSummariesResponse). Keep these fields
// in step with the C# DTOs.
//
// Every request is root-relative to the Gateway front door (Gateway-only-ingress, #967): a Director
// address never reaches the browser. The per-device Bearer rides through the shared authHeaders().
import { GatewayError, authHeaders } from "../api/client";

/**
 * GET/POST /sessions/{sid}/recap response. The recap is markdown text ("## What was done" /
 * "## What is next") generated by a side-model call against a digest of the session (NOT by prompting
 * the live session). Mirrors CcDirector.Gateway.Contracts.RecapResponse.
 */
export interface RecapResponse {
  sessionId: string;
  /** The recap text (markdown). Empty when status != "ok". */
  recap: string;
  /** UTC timestamp (ISO 8601) the cached recap was generated, or null when none. */
  generatedAt?: string | null;
  /** Turn count at the time the recap was generated. */
  atTurnCount: number;
  /** Current turn count when this response was built. */
  currentTurnCount: number;
  /** True when the session has had new turns since this recap was made (caller may regenerate). */
  isStale: boolean;
  /** The model used to generate the recap (e.g. "opus", "haiku"). */
  model: string;
  /** Elapsed milliseconds the side-model call took. */
  elapsedMs: number;
  /** "ok" | "not_cached" | "no_session_id" | "no_jsonl" | "generation_failed". */
  status: string;
  /** Free-text error message when status != "ok". */
  error?: string | null;
}

/**
 * One completed turn's summary (the Wingman per-turn summariser). Mirrors
 * CcDirector.Gateway.Contracts.TurnSummary (only the fields the awareness turn rail renders are
 * documented; the DTO carries the TTS/spoken fields too).
 */
export interface TurnSummary {
  /** UTC timestamp (ISO 8601) this summary was produced. */
  generatedAt: string;
  /** UTC timestamp (ISO 8601) the turn itself started. */
  turnStartedAt: string;
  /** One short sentence describing what the agent did this turn. */
  headline: string;
  /** Distinct file paths touched this turn (max 5). */
  filesTouched: string[];
  /** Distinct shell commands run this turn (max 3). */
  commandsRun: string[];
  /** Key decisions / findings the agent surfaced (max 3). */
  decisions: string[];
  /** "no" | "question" | "error" | "permission" | "idle". */
  needsUser: string;
  /** Short sentence elaborating needsUser when not "no". */
  needsUserDetail: string;
  /** "ok" | "wingman_failed" | "parse_failed". */
  status: string;
  /** Free-text error detail when status != "ok". */
  error?: string | null;
}

/**
 * Response shape of GET /sessions/{sid}/turn-summaries - the cached list of summaries for one session,
 * ordered oldest -> newest. Mirrors CcDirector.Gateway.Contracts.TurnSummariesResponse.
 */
export interface TurnSummariesResponse {
  sessionId: string;
  summaries: TurnSummary[];
}

/**
 * The cached "what's happening" recap (GET /sessions/{sid}/recap). Fast/free - reads the in-process
 * cache; status is "not_cached" until one is generated. The endpoint returns 200 even when nothing is
 * cached (the status field carries that), so a non-2xx is a real transport error, not "no recap".
 */
export async function getRecap(sessionId: string, signal?: AbortSignal): Promise<RecapResponse> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/recap`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET recap failed: ${res.status}`);
  }
  return (await res.json()) as RecapResponse;
}

/**
 * Generate a fresh recap (POST /sessions/{sid}/recap). SLOW - a Director-side opus call (~90s). This
 * fetch is client-side and independent of the terminal's WebSocket, so the long generation never
 * blocks or freezes the live terminal (that is a separate stream); the caller shows progress while it
 * runs and swaps in the result when it lands.
 */
export async function generateRecap(sessionId: string, signal?: AbortSignal): Promise<RecapResponse> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/recap`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST recap failed: ${res.status}`);
  }
  return (await res.json()) as RecapResponse;
}

/**
 * The session's turn-by-turn summaries (GET /sessions/{sid}/turn-summaries) - the arc of the session,
 * oldest -> newest. Fast/free - reads cached summaries. Returns an empty list (never null) on a 404
 * from an old Director or a session it no longer knows, so the turn rail simply shows "no turns yet".
 */
export async function getTurnSummaries(
  sessionId: string,
  signal?: AbortSignal,
): Promise<TurnSummariesResponse> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/turn-summaries`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (res.status === 404) return { sessionId, summaries: [] };
  if (!res.ok) {
    throw new GatewayError(res.status, `GET turn-summaries failed: ${res.status}`);
  }
  return (await res.json()) as TurnSummariesResponse;
}
