# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src\\cli.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'src',
        'src.cli',
        'src.models',
        'src.runner',
        'src.aggregator',
        'src.browser_client',
        'src.sources',
        'src.sources.base',
        'src.sources.company_website',
        'src.sources.fec_donations',
        'src.sources.github_search',
        'src.sources.google_dorking',
        'src.sources.gravatar',
        'src.sources.linkedin',
        'src.sources.nuwber',
        'src.sources.opencorporates',
        'src.sources.sec_edgar',
        'src.sources.thatsthem',
        'src.sources.truepeoplesearch',
        'src.sources.wayback',
        'src.sources.whois_lookup',
        'src.sources.zabasearch',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='cc-personresearch',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
