// <auto-generated />
using CcDirector.Gateway.Tests.Data.StatsSchemaProof;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CcDirector.Gateway.Tests.Data.StatsSchemaProof.Migrations
{
    [DbContext(typeof(StatsSchemaProofDbContext))]
    partial class StatsSchemaProofDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gateway_stats")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CcDirector.Gateway.Tests.Data.StatsSchemaProof.ProofDeltaRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Chars")
                        .HasColumnType("bigint")
                        .HasColumnName("chars");

                    b.Property<string>("HourUtc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hour_utc");

                    b.Property<string>("Tenant")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.Property<long>("Turns")
                        .HasColumnType("bigint")
                        .HasColumnName("turns");

                    b.HasKey("Id");

                    b.HasIndex("Tenant", "HourUtc")
                        .HasDatabaseName("ix_proof_delta_tenant_hour");

                    b.ToTable("proof_delta", "gateway_stats");
                });

            modelBuilder.Entity("CcDirector.Gateway.Tests.Data.StatsSchemaProof.ProofHighwaterRow", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<long>("Turns")
                        .HasColumnType("bigint")
                        .HasColumnName("turns");

                    b.HasKey("Tenant", "SessionId");

                    b.ToTable("proof_highwater", "gateway_stats");
                });

            modelBuilder.Entity("CcDirector.Gateway.Tests.Data.StatsSchemaProof.ProofMetaRow", b =>
                {
                    b.Property<string>("Tenant")
                        .HasColumnType("text")
                        .HasColumnName("tenant");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Tenant", "Name");

                    b.ToTable("proof_meta", "gateway_stats");
                });
#pragma warning restore 612, 618
        }
    }
}
