// <auto-generated />
using System;
using CcDirector.Gateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CcDirector.Gateway.Data.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260717230354_AddWorkLists")]
    partial class AddWorkLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.CronJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFiredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyOn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NotifyWebhookUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreventOverlap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScheduleKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("cron_jobs", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.CronRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FiredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfraStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetDirectorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("JobId", "Sequence");

                    b.ToTable("cron_runs", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("worklists", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkListItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkListId", "Position");

                    b.ToTable("worklist_items", (string)null);
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.CronJobEntity", b =>
                {
                    b.OwnsOne("CcDirector.Gateway.Contracts.CronJobAction", "Action", b1 =>
                        {
                            b1.Property<string>("CronJobEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("AutoDismiss")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RepoPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Seed")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("WorkListName")
                                .HasColumnType("TEXT");

                            b1.HasKey("CronJobEntityId");

                            b1.ToTable("cron_jobs");

                            b1.ToJson("Action");

                            b1.WithOwner()
                                .HasForeignKey("CronJobEntityId");
                        });

                    b.OwnsOne("CcDirector.Gateway.Contracts.CronJobTarget", "Target", b1 =>
                        {
                            b1.Property<string>("CronJobEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Machine")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CronJobEntityId");

                            b1.ToTable("cron_jobs");

                            b1.ToJson("Target");

                            b1.WithOwner()
                                .HasForeignKey("CronJobEntityId");
                        });

                    b.Navigation("Action")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkListItemEntity", b =>
                {
                    b.HasOne("CcDirector.Gateway.Data.Entities.WorkListEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("WorkListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkListEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
