// Typed Gateway client. The TYPES come from the OpenAPI document the Gateway emits
// (src/api/schema.ts, generated by `npm run gen:api`), so the C# DTOs stay the single source
// of truth: a C# DTO change that is not reflected in a regenerated schema fails this build.
//
// The credential on every call is the PER-DEVICE KEY this browser obtained at enrollment
// (issue #908 for the phone, issue #1088 for the desktop Cockpit) - the one standing credential in
// the system. No token is injected into the page; the shell carries no secret until the person
// signs in on devthrottle.com and the device enrolls with the Gateway.
import type { components } from "./schema";
import type { SessionHistoryDto } from "../history/types";
import { planUploadChunks } from "./chunking";
import { getDeviceKey, clearDeviceKey } from "../auth/deviceKey";
import { publishDictationStatus } from "../dictation/status";

export type SessionDto = components["schemas"]["SessionDto"];

// Request bodies are typed from the generated OpenAPI schema (the C# DTOs stay the source of
// truth). The buffer/escape/interrupt/transcription responses are not declared in the schema (the
// Gateway returns them via Results.Json without a [Produces] annotation), so they are read with
// narrow local shapes for exactly the fields the mobile views consume.
type PromptRequest = components["schemas"]["PromptRequest"];
type NewSessionRequest = components["schemas"]["NewSessionRequest"];

// One machine (Director) in the fleet, projected from GET /directors. The response is not declared
// in the OpenAPI schema (the Gateway returns it via Results.Json without a [Produces] annotation),
// so it is read with this narrow local shape - the exact subset the add-session flow consumes,
// mirroring the Android phone/CcDirectorClient DirectorInfo.
export interface DirectorInfo {
  directorId: string;
  machineName: string;
  /** Best-effort version label for the picker subtitle. */
  version: string;
  /** When the Director process started (ISO 8601 UTC), or empty. Drives the picker "up <uptime> /
   *  started <when>" subtitle (issue #848); empty/unparseable degrades to last-seen only. */
  startedAt: string;
  /** When the Gateway last heard from this Director (ISO 8601), or empty. Used to default-select. */
  lastSeen: string;
}

// One recently-used repository on a Director, projected from GET /directors/{id}/repos. Also not in
// the OpenAPI schema; read with this narrow local shape, mirroring the Android RepoInfo.
export interface RepoInfo {
  name: string;
  path: string;
  /** When a session last used this repo (ISO 8601), or empty. The list is sorted newest-used first. */
  lastUsed: string;
}

// The app's credential is the per-device key it obtained at enrollment (issue #908/#1088), read from
// the device-key store - NOT a token injected into the page (the shell carries no secret). Empty until
// this device has enrolled, in which case the caller (the auth gate) routes to the Sign in screen.
function gatewayToken(): string {
  return getDeviceKey();
}

// Exported so the dictation transcription calls (which post raw audio bytes and read a transcript)
// attach the same Bearer the rest of the client uses. Empty headers before enrollment; the app gates
// on the device key so no data call runs without one.
export function authHeaders(): HeadersInit {
  const token = gatewayToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

// Mirror the per-device key into the cc-gateway-token cookie (issue #817/#908). A browser WebSocket
// cannot set an Authorization header, so the live terminal stream (GET /sessions/{sid}/stream)
// authenticates via this cookie, which the same-origin handshake carries and the Gateway's
// AuthMiddleware accepts (HasValidToken checks the cookie against the shared token OR an active
// per-device key). The key is already in this origin's storage, so the cookie exposes nothing new; it
// is scoped to this origin. A no-op before enrollment (no key yet - the stream is never opened then).
export function ensureGatewayCookie(): void {
  const token = gatewayToken();
  if (!token) return;
  document.cookie = `cc-gateway-token=${encodeURIComponent(token)}; path=/; SameSite=Lax`;
}

// The redirect target when a credentialed call is rejected (401) mid-session is SHELL-AWARE, because
// the two shells that share this client re-gate through sign-in entries at different paths: the
// mobile PWA's enrollment screen lives at /m/signin, the desktop Cockpit's at /signin. Shared
// client-core must NOT hardcode either shell's route for the other (issue #1024), so the target is
// INJECTED per shell at startup via configureUnauthorizedRedirect. The resolver is given the current
// in-app location so a shell that carries the route forward (the desktop next=) can build a
// round-trip target.
export interface SignInLocation {
  pathname: string;
  search: string;
}
export type SignInRedirect = (current: SignInLocation) => string;

// The desktop Cockpit's sign-in redirect (issue #1088): re-gate through the Cockpit's own /signin
// route - the SAME shared client-core enrollment flow the phone uses - carrying the current route in
// next= so the browser lands back where it was once this device is enrolled again. This replaced the
// former /login token-wall re-gate (the raw-token wall is break-glass only, issue #1077): after a
// website revoke the desktop returns to the shared sign-in flow, never to login.html.
export function cockpitSignInRedirect(current: SignInLocation): string {
  return `/signin?next=${encodeURIComponent(current.pathname + current.search)}`;
}

// The mobile PWA's sign-in redirect: its own /m/signin enrollment screen, absolute under the /m
// basename so it works from any in-app route. This is what the mobile shell installs at startup, and it
// is the default so an unconfigured client-core still serves the shell that historically owned it.
export function mobileSignInRedirect(): string {
  return "/m/signin";
}

let signInRedirect: SignInRedirect = mobileSignInRedirect;

// Each shell installs its own sign-in redirect at startup (the mobile PWA -> mobileSignInRedirect, the
// desktop Cockpit -> cockpitSignInRedirect), so a mid-session 401 re-gates through the entry that shell
// actually uses instead of the mobile route baked into shared client-core (issue #1024).
export function configureUnauthorizedRedirect(redirect: SignInRedirect): void {
  signInRedirect = redirect;
}

// The configured sign-in target for the given current location. Exported so onUnauthorized has one
// place to resolve it and the shell-aware behavior is unit-testable without a DOM.
export function resolveSignInTarget(current: SignInLocation): string {
  return signInRedirect(current);
}

// Called when the Gateway answers 401 to a credentialed call: the device key was revoked (from the
// website's "Your devices") or is otherwise no longer valid. Forget it and send the user back to the
// shell's own Sign in entry, so a revoke on the account promptly ends access (the revoke round-trip,
// issue #908). A hard navigation (not the router) guarantees the whole app re-gates from a clean state.
function onUnauthorized(): void {
  clearDeviceKey();
  if (typeof window === "undefined") return;
  const target = resolveSignInTarget({
    pathname: window.location.pathname,
    search: window.location.search,
  });
  // Compare on the path only so a resolver that appends a query (the desktop next=) does not loop
  // when the browser is already sitting on the sign-in entry.
  const targetPath = target.split("?")[0];
  if (window.location.pathname !== targetPath) {
    window.location.assign(target);
  }
}

export class GatewayError extends Error {
  readonly status: number;
  constructor(status: number, message: string) {
    super(message);
    this.name = "GatewayError";
    this.status = status;
  }
}

// The shared "hosted AI is unavailable" body every money endpoint returns on HTTP 402 (issue #939/#941;
// consumed by mobile in #942): the single-source message + call-to-action. `text` is the message to show;
// `ctaUrl` deep-links to Billing.
export interface HostedAiUnavailable {
  state: string;      // "NeedsCredits" | "CapReached" | "NeedsKey"
  text: string;
  ctaLabel: string;
  ctaAction: string;  // "OpenBilling" | "OpenSettings"
  ctaUrl: string | null;
}

// A 402 from a hosted-AI call (out of credits / cap / no key). Its `message` IS the shared text, so any
// surface that already shows `err.message` displays the correct copy by construction; `info` carries the
// call-to-action for the app-level notice (issue #942).
export class CreditsError extends GatewayError {
  readonly info: HostedAiUnavailable;
  constructor(info: HostedAiUnavailable) {
    super(402, info.text || info.state || "Voice needs credit.");
    this.name = "CreditsError";
    this.info = info;
  }
}

// App-level subscription so ONE notice (with the "Add credits" button) shows wherever a 402 happens,
// without every surface widening its string error state. The client emits on every hosted-AI 402; the
// app renders a single CreditsNotice. Returns an unsubscribe function.
type CreditsListener = (info: HostedAiUnavailable) => void;
const creditsListeners = new Set<CreditsListener>();
export function onCreditsNeeded(fn: CreditsListener): () => void {
  creditsListeners.add(fn);
  return () => { creditsListeners.delete(fn); };
}

// Build a CreditsError from an already-parsed 402 body and notify the app-level notice. Defaults keep the
// message correct even if a field is missing. Call from the `!res.ok` branch of any hosted-AI call when
// `res.status === 402` (the body is already the shared shape from the Gateway).
export function creditsErrorFrom(body: unknown): CreditsError {
  const b = (body ?? {}) as Partial<HostedAiUnavailable> & { error?: string };
  const info: HostedAiUnavailable = {
    state: b.state ?? "NeedsCredits",
    text: b.text ?? b.error ?? "Voice needs credit. Add credits to turn it on.",
    ctaLabel: b.ctaLabel ?? "Add credits",
    ctaAction: b.ctaAction ?? "OpenBilling",
    ctaUrl: b.ctaUrl ?? null,
  };
  for (const fn of creditsListeners) { try { fn(info); } catch { /* a listener must never break the throw */ } }
  return new CreditsError(info);
}

// The single user-facing line for "the Gateway is unreachable", shared by every page that reads the
// Gateway on a poll (issue #1028). It implies the automatic retry those pages already perform, so the
// copy is truthful wherever it appears.
export const GATEWAY_UNREACHABLE_MESSAGE = "Can't reach the Gateway - retrying.";

// True when an error means the request never reached a healthy backend: the browser's bare fetch
// rejection when the Gateway is down (a TypeError, not a GatewayError), or a Gateway/proxy status
// that signals it could not reach the backend (Bad Gateway, Service Unavailable, Gateway Timeout, or
// a synthetic 0). These are the "unreachable" cases, distinct from a reachable Gateway that answered
// with an application error (400/404/409/500).
function isGatewayUnreachable(err: unknown): boolean {
  if (err instanceof GatewayError) {
    return err.status === 0 || err.status === 502 || err.status === 503 || err.status === 504;
  }
  return err instanceof Error;
}

// Map any error thrown by a Gateway read/write into ONE user-facing line, never leaking the internal
// "METHOD /path failed: NNN" diagnostic the client throws on a non-2xx, nor the browser's bare
// "Failed to fetch" when the backend is down (issue #1028). An unreachable Gateway collapses to the
// shared friendly, retry-implying line; a GatewayError that already carries human copy (a 401 re-auth
// prompt, a 402 credits notice) is returned verbatim; any other reachable-but-erroring status is
// reported by its number only, without the raw method and path.
export function gatewayErrorMessage(err: unknown): string {
  if (isGatewayUnreachable(err)) return GATEWAY_UNREACHABLE_MESSAGE;
  if (err instanceof CreditsError) return err.message;
  if (err instanceof GatewayError) {
    if (err.status === 401) return err.message;
    return `The Gateway rejected the request (error ${err.status}).`;
  }
  return GATEWAY_UNREACHABLE_MESSAGE;
}

// GET /sessions - the fleet roster aggregator. Returns the same SessionDto shape the Cockpit
// Mobile page consumes. Throws GatewayError on a non-2xx so the caller surfaces it (no silent
// fallback). The request is same-origin against the Gateway front door.
export async function listSessions(signal?: AbortSignal): Promise<SessionDto[]> {
  const res = await fetch("/sessions", {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (res.status === 401) {
    // The device key was revoked (or is otherwise invalid): forget it and re-gate to Sign in. The
    // roster is the first credentialed call the app makes, so this is where a revoke surfaces.
    onUnauthorized();
    throw new GatewayError(res.status, "This device is no longer authorized. Please sign in again.");
  }
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /sessions failed: ${res.status}`);
  }
  return (await res.json()) as SessionDto[];
}

// GET /sessions/{sid}/history - the parsed, agent-agnostic conversation history for one session
// (issue #811). The Director's SessionHistoryEndpoint returns SessionHistoryDto; the Gateway
// forwards it verbatim through the catch-all /sessions/{sid}/{**rest} proxy with the injected
// Bearer (no backend change), exactly the way Terminal reaches /prompt. The shape is not declared
// in the OpenAPI schema (it rides the generic per-session proxy), so it is read with the narrow
// local SessionHistoryDto type. A 404 (old Director / unknown session) is surfaced as a
// GatewayError so the caller can treat it as "nothing yet" rather than a hard failure.
export async function getSessionHistory(
  sessionId: string,
  signal?: AbortSignal,
): Promise<SessionHistoryDto> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/history`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET history failed: ${res.status}`);
  }
  return (await res.json()) as SessionHistoryDto;
}

// Write text (or a raw key escape sequence) to the session's PTY. appendEnter=true submits a typed
// line (the Send button); appendEnter=false writes the bytes verbatim (Enter "\r", arrow keys
// ESC[A/B/C/D) so the session reacts as if the key were pressed at the terminal.
export async function sendPrompt(
  sessionId: string,
  text: string,
  appendEnter: boolean,
  signal?: AbortSignal,
): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const body: PromptRequest = { text, appendEnter };
  const res = await fetch(`/sessions/${sid}/prompt`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST prompt failed: ${res.status}`);
  }
}

// Soft-stop the current turn (the agent driver's Escape). POST /sessions/{sid}/escape.
export async function sendEscape(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/escape`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST escape failed: ${res.status}`);
  }
}

// Interrupt a running agent turn (Ctrl+C). POST /sessions/{sid}/interrupt.
export async function sendInterrupt(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/interrupt`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST interrupt failed: ${res.status}`);
  }
}

// Reset the conversation context in place (/clear for Claude, /new for pi) without ending the
// process. POST /sessions/{sid}/clear-context. Only meaningful for drivers that declare the
// ClearContext capability; the caller gates the button on SessionDto.driverCapabilities.
export async function sendClearContext(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/clear-context`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST clear-context failed: ${res.status}`);
  }
}

// Open the tool's in-terminal history / rewind picker (Claude's double-Esc). POST
// /sessions/{sid}/history-picker. Gated on the History capability - a visible-terminal feature.
export async function sendHistoryPicker(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/history-picker`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST history-picker failed: ${res.status}`);
  }
}

// ===== Prompt queue (issue #972): the composer's Queue and the queue panel verbs =====
// A faithful port of the Blazor Cockpit DirectorClient queue methods. Every verb returns the
// server's authoritative queue (the owning Director owns the ordered list), so the caller
// replaces its whole list from the response rather than mutating optimistically. All routes are
// root-relative to the Gateway, which forwards the session-scoped verb to the owning Director.

/** One queued prompt, as returned by GET /sessions/{sid}/queue on a Director. */
export interface QueueItem {
  id: string;
  text: string;
  /** ISO 8601 UTC when the item was queued. */
  createdAt: string;
}

// Read the response's { items } as the authoritative queue. Shared by every queue verb so the
// parse lives in one place; a non-2xx throws so the caller surfaces it (no silent empty queue).
async function readQueue(res: Response, label: string): Promise<QueueItem[]> {
  if (!res.ok) {
    throw new GatewayError(res.status, `${label} failed: ${res.status}`);
  }
  const body = (await res.json().catch(() => ({}))) as { items?: QueueItem[] };
  return body.items ?? [];
}

// GET /sessions/{sid}/queue - the session's current queued prompts, in order.
export async function getQueue(sessionId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/queue`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "GET queue");
}

// POST /sessions/{sid}/queue { text } - append a prompt to the queue; returns the new queue.
export async function enqueuePrompt(sessionId: string, text: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/queue`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ text }),
    signal,
  });
  return readQueue(res, "POST queue");
}

// DELETE /sessions/{sid}/queue/{itemId} - remove one item; returns the remaining queue.
export async function deleteQueueItem(sessionId: string, itemId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}`, {
    method: "DELETE",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "DELETE queue item");
}

// POST /sessions/{sid}/queue/{itemId}/send - submit one queued item now; returns the remaining queue.
export async function sendQueueItem(sessionId: string, itemId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}/send`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "POST queue send");
}

// PATCH /sessions/{sid}/queue/{itemId} { text } - edit one item's text; returns the updated queue.
export async function editQueueItem(sessionId: string, itemId: string, text: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ text }),
    signal,
  });
  return readQueue(res, "PATCH queue item");
}

// POST /sessions/{sid}/queue/{itemId}/move-up - move one item earlier; returns the reordered queue.
export async function moveQueueItemUp(sessionId: string, itemId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}/move-up`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "POST queue move-up");
}

// POST /sessions/{sid}/queue/{itemId}/move-down - move one item later; returns the reordered queue.
export async function moveQueueItemDown(sessionId: string, itemId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}/move-down`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "POST queue move-down");
}

// DELETE /sessions/{sid}/queue - clear the whole queue; returns the (empty) queue.
export async function clearQueue(sessionId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/queue`, {
    method: "DELETE",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "DELETE queue");
}

// ===== Screenshots gallery (issue #972): the captured-screenshots folder on the owning Director =====
// A faithful port of the Blazor DirectorClient screenshots methods. The folder is per-machine on the
// Director, but the Cockpit always asks in the context of the selected session, so the session id is
// the routing key and the Gateway forwards to the owning Director's machine-wide folder. The image
// BYTES are loaded by the browser same-origin through the Gateway's per-session proxy
// (screenshotFileUrl), so no absolute Director address ever reaches the page (issue #317 / #967).

/** One screenshot on a Director's machine. The Director pre-formats timeLabel so every surface
 *  shows the same label without re-deriving it. */
export interface ScreenshotInfo {
  fileName: string;
  /** Absolute on-disk path on the Director's machine, injected into the composer so the owning
   *  agent can read the image directly (no upload). */
  path: string;
  timeLabel: string;
  lastWriteUtc: string;
  sizeBytes: number;
}

/** GET /sessions/{sid}/screenshots: the resolved folder + its newest image files. */
export interface ScreenshotsResult {
  directory: string;
  /** Full folder count regardless of any count cap; 0 on old Directors (treat items.length as total). */
  total: number;
  items: ScreenshotInfo[];
}

// The same-origin URL for a screenshot's bytes, used as the thumbnail <img src> and the "view
// full size" link. Root-relative to the Gateway (never a Director address), so a Director that
// advertises only a loopback endpoint still renders correctly for a remote browser (issue #317).
export function screenshotFileUrl(sessionId: string, fileName: string): string {
  const sid = encodeURIComponent(sessionId);
  return `/sessions/${sid}/screenshots/file?name=${encodeURIComponent(fileName)}`;
}

// GET /sessions/{sid}/screenshots[?count=N] - the newest screenshots' metadata (not the bytes).
// count <= 0 fetches everything (the folder can hold thousands, so callers pass a cap). A 503 means
// the owning Director is offline (the Gateway could not reach it for this leg, issue #412); it is
// surfaced as a GatewayError so the caller can show a graceful "Director offline" state + Retry.
export async function getScreenshots(sessionId: string, count = 0, signal?: AbortSignal): Promise<ScreenshotsResult> {
  const sid = encodeURIComponent(sessionId);
  const path = count > 0 ? `/sessions/${sid}/screenshots?count=${count}` : `/sessions/${sid}/screenshots`;
  const res = await fetch(path, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET screenshots failed: ${res.status}`);
  }
  const body = (await res.json().catch(() => ({}))) as Partial<ScreenshotsResult>;
  return {
    directory: body.directory ?? "",
    total: Number(body.total ?? 0),
    items: body.items ?? [],
  };
}

// DELETE /sessions/{sid}/screenshots/file?name=... - delete one screenshot file from the Director's disk.
export async function deleteScreenshot(sessionId: string, fileName: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/screenshots/file?name=${encodeURIComponent(fileName)}`, {
    method: "DELETE",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `DELETE screenshot failed: ${res.status}`);
  }
}

// POST /sessions/{sid}/upload-image (multipart, field "file") - forward a device-local image to the
// owning Director, which saves it to its Screenshots folder and returns the absolute on-disk path.
// The caller inserts that path into the composer so the agent can read the image directly; the
// upload endpoint itself injects nothing into the session.
export async function uploadImage(sessionId: string, file: File, signal?: AbortSignal): Promise<string> {
  const sid = encodeURIComponent(sessionId);
  const form = new FormData();
  form.append("file", file, file.name);
  const res = await fetch(`/sessions/${sid}/upload-image`, {
    method: "POST",
    headers: { ...authHeaders() },
    body: form,
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST upload-image failed: ${res.status}`);
  }
  const body = (await res.json().catch(() => ({}))) as { path?: string };
  return body.path ?? "";
}

// ===== Session management (issue #812): the add-session flow + Hold/Resume + Remove =====
// A faithful 1:1 of the Android (MAUI) phone/CcDirectorClient "+ New session" flow and the
// owner's Hold/Remove decision. Every call carries the same Bearer the rest of the client uses, so
// the whole flow works with global Gateway auth on or off.

// GET /directors - the fleet's machines (Directors). Sorted most-recently-seen first so the picker
// can default-select the top one (matching FleetParser.ParseDirectors), tie-broken by machine name.
// Entries with no directorId are dropped (they cannot be addressed). Throws GatewayError on non-2xx
// so the picker shows the real reason instead of a silently empty list.
export async function getDirectors(signal?: AbortSignal): Promise<DirectorInfo[]> {
  const res = await fetch("/directors", {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /directors failed: ${res.status}`);
  }
  const raw = (await res.json()) as Array<Record<string, unknown>>;
  const list: DirectorInfo[] = raw
    .map((d) => ({
      directorId: String(d.directorId ?? ""),
      machineName: String(d.machineName ?? ""),
      version: String(d.version ?? ""),
      startedAt: String(d.startedAt ?? ""),
      lastSeen: String(d.lastSeen ?? ""),
    }))
    .filter((d) => d.directorId.length > 0);
  list.sort((a, b) => {
    const bySeen = b.lastSeen.localeCompare(a.lastSeen); // newest-seen first (ISO 8601 sorts lexically)
    if (bySeen !== 0) return bySeen;
    return a.machineName.localeCompare(b.machineName);
  });
  return list;
}

// GET /directors/{id}/repos - a machine's recently-used repositories, sorted newest-used first
// (the server already sorts this way; we re-sort so a mixed body is still correct, matching
// FleetParser.ParseRepos). Entries with no path are dropped. Throws GatewayError on non-2xx.
export async function getRepos(directorId: string, signal?: AbortSignal): Promise<RepoInfo[]> {
  const id = encodeURIComponent(directorId);
  const res = await fetch(`/directors/${id}/repos`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /directors/${directorId}/repos failed: ${res.status}`);
  }
  const raw = (await res.json()) as Array<Record<string, unknown>>;
  const list: RepoInfo[] = raw
    .map((r) => ({
      name: String(r.name ?? ""),
      path: String(r.path ?? ""),
      lastUsed: String(r.lastUsed ?? ""),
    }))
    .filter((r) => r.path.length > 0);
  list.sort((a, b) => b.lastUsed.localeCompare(a.lastUsed)); // newest-used first
  return list;
}

// POST /directors/{id}/sessions - create a new session in repoPath. Agent is hardcoded "ClaudeCode"
// and wingmanEnabled=false, type omitted, exactly like the Android NewSessionPanel
// (FleetParser.BuildCreateBody). Returns the created SessionDto so the caller can open it. The
// Gateway answers 201 on success; throws GatewayError on non-2xx with the server's reason.
export async function createSession(
  directorId: string,
  repoPath: string,
  signal?: AbortSignal,
): Promise<SessionDto> {
  const id = encodeURIComponent(directorId);
  const body: NewSessionRequest = { repoPath: repoPath.trim(), agent: "ClaudeCode", wingmanEnabled: false };
  const res = await fetch(`/directors/${id}/sessions`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok) {
    let detail = `${res.status}`;
    try {
      const err = (await res.json()) as { detail?: string; error?: string };
      detail = err.detail ?? err.error ?? detail;
    } catch {
      /* non-JSON error body - keep the status code */
    }
    throw new GatewayError(res.status, `Create session failed: ${detail}`);
  }
  return (await res.json()) as SessionDto;
}

// POST /sessions/{sid}/hold - toggle the session's on-hold state. The desired state is sent
// explicitly ({ onHold }) so the call is idempotent; the Director echoes the applied { onHold }.
// Reaches the Director through the Gateway catch-all session proxy with the injected Bearer.
export async function holdSession(
  sessionId: string,
  onHold: boolean,
  signal?: AbortSignal,
): Promise<boolean> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/hold`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ onHold }),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST hold failed: ${res.status}`);
  }
  const result = (await res.json().catch(() => ({}))) as { onHold?: boolean };
  return result.onHold ?? onHold;
}

// POST /sessions/{sid}/transcribing - mark or clear this session as transcribing a dictated
// utterance in the background (the phone hit Send in the Speak dialog and released the screen). This
// is a Gateway-owned transient flag ONLY - it is not forwarded to the Director; it drives the orange
// "Transcribing..." roster color so nobody else starts using the session while its audio is being
// uploaded and transcribed. Sent true the instant Send is pressed and false once the background
// upload/transcribe/submit finishes or fails. Reaches a Gateway-native literal route (no Director
// hop) with the injected Bearer.
export async function setTranscribing(
  sessionId: string,
  transcribing: boolean,
  signal?: AbortSignal,
): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/transcribing`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ transcribing }),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST transcribing failed: ${res.status}`);
  }
}

// DELETE /sessions/{sid} - kill the agent process and remove the session from the roster (the
// Android kill/remove semantics, gated behind a confirmation per the owner's #545 request). Reaches
// the Director through the Gateway catch-all session proxy with the injected Bearer.
export async function killSession(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}`, {
    method: "DELETE",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `DELETE session failed: ${res.status}`);
  }
}

// Dictation transcription (issue #817). Speech-to-text for the Speak dialog uses the unified
// Gateway transcription job protocol: register -> chunk -> complete. Clients capture and preserve
// audio; the Gateway owns provider selection, transcription, correction, status, retries, and
// provenance.
//
// The optional client-measured capture-health fields are kept on the complete call for diagnostics.
// Older Gateway builds may ignore them; they do not change the transcription contract.
export interface UtteranceCaptureHealth {
  recordedMs: number;
  decodedSeconds: number;
  sourceBytes: number;
}

// The largest a single upload chunk may be. A long recording is uploaded as several chunks of at
// most this size so no single request body exceeds the Gateway limit (Kestrel's default is roughly
// thirty megabytes; a twenty-minute clip is larger). This is independent of how the server later
// splits the reassembled clip into bounded transcription requests - it only bounds the upload hop.
const MAX_UPLOAD_CHUNK_BYTES = 5_000_000;

export async function transcribeUtterance(
  wav: Blob,
  health?: UtteranceCaptureHealth,
  signal?: AbortSignal,
  onProgress?: (uploadedChunks: number, totalChunks: number) => void,
): Promise<string> {
  // 1. Register the job (mints an id the chunk + complete calls address).
  const reg = await fetch(`/transcription/upload`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({
      action: "return_transcript",
      contentType: "audio/wav",
      extension: "wav",
      applyCorrection: true,
    }),
    signal,
  });
  if (!reg.ok) {
    throw new GatewayError(reg.status, `POST transcription/upload failed: ${reg.status}`);
  }
  const regBody = (await reg.json()) as { jobId?: string; upload_id?: string };
  const jobId = regBody.jobId ?? regBody.upload_id;
  if (!jobId) {
    throw new GatewayError(reg.status, "transcription register returned no job id");
  }

  // 2. Upload the WAV in bounded chunks so a long recording never exceeds the Gateway request-body
  //    limit. Each chunk carries its own SHA256, so the server rejects corruption and treats a
  //    retried chunk as a free no-op; the server reassembles the chunks in order before transcribing.
  const bytes = new Uint8Array(await wav.arrayBuffer());
  const id = encodeURIComponent(jobId);
  const ranges = planUploadChunks(bytes.length, MAX_UPLOAD_CHUNK_BYTES);
  onProgress?.(0, ranges.length);
  for (const range of ranges) {
    const part = bytes.subarray(range.start, range.end);
    const sha = await sha256Hex(part);
    const put = await fetch(`/transcription/${id}/chunk/${range.index}`, {
      method: "PUT",
      headers: { "Content-Type": "application/octet-stream", "X-Chunk-Sha256": sha, ...authHeaders() },
      body: part,
      signal,
    });
    if (!put.ok) {
      throw new GatewayError(put.status, `PUT transcription chunk ${range.index} failed: ${put.status}`);
    }
    onProgress?.(range.index + 1, ranges.length);
  }

  // 3. Complete with the real chunk count -> the server reassembles all chunks, transcribes the clip
  //    (the pipeline itself splits the reassembled audio into bounded transcription requests), applies
  //    the dictionary correction, and returns the cleaned transcript.
  const comp = await fetch(`/transcription/${id}/complete`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({
      totalChunks: ranges.length,
      mime: "audio/wav",
      ext: "wav",
      applyCorrection: true,
      clientRecordedMs: health?.recordedMs,
      clientDecodedSeconds: health?.decodedSeconds,
      clientSourceBytes: health?.sourceBytes,
    }),
    signal,
  });
  const compBody = (await comp.json().catch(() => ({}))) as {
    transcript?: string;
    cleanedTranscript?: string;
    rawTranscript?: string;
    error?: string;
  };
  if (!comp.ok) {
    // Out of credits / cap (issue #942): a typed CreditsError carrying the shared message + call-to-action.
    if (comp.status === 402) throw creditsErrorFrom(compBody);
    throw new GatewayError(comp.status, compBody.error ?? `transcription failed: ${comp.status}`);
  }
  return (compBody.transcript ?? compBody.cleanedTranscript ?? compBody.rawTranscript ?? "").trim();
}

// Hex SHA256 of the upload bytes via the Web Crypto API (available in any secure context, which a
// microphone-capable page already is).
async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// ===== Durable, server-owned dictation upload (issue #1006) =====================================
// Streams the raw recorded audio to the Gateway in resumable, SHA-checked chunks; the Gateway then
// assembles, transcribes, and INJECTS the turn into the session itself. Once every chunk is up the
// turn lands even if this tab dies. Idempotent by uploadId, so a resume re-runs safely.

/** Outcome of a durable dictation submit. `terminal` means the server handled it (submitted or
 *  dropped as stale) and the durable local copy can be deleted; otherwise retry it on resume. */
export interface DictationSubmitResult {
  terminal: boolean;
  submitted: boolean;
  movedOn: boolean;
  transcript: string;
  error?: string;
}

export interface DictationUploadArgs {
  sessionId: string;
  /** The durable record id; also the server upload id and Idempotency-Key. */
  uploadId: string;
  /** Raw recorded audio exactly as the microphone produced it. */
  audio: Blob;
  before: string;
  after: string;
  prefix: string;
  baselineBufferBytes: number;
  resumed: boolean;
}

const CHUNK_RETRIES = 4;

export async function uploadDictationToSession(
  args: DictationUploadArgs,
  signal?: AbortSignal,
): Promise<DictationSubmitResult> {
  // Live status is published at every step so the on-screen strip and the roster badge show exactly
  // where the send is (owner rule after #1139: never a silent dictation). A failure is published as a
  // sticky, retryable status rather than only returned, so it cannot be lost if the caller is gone.
  const sid = args.sessionId;
  const uploadId = args.uploadId;
  const failed = (error: string, retryable = true): DictationSubmitResult => {
    publishDictationStatus({ sessionId: sid, uploadId, phase: "failed", error, retryable });
    return { terminal: false, submitted: false, movedOn: false, transcript: "", error };
  };

  // 1. Register (idempotent: the same id re-opens the same staging after a resume).
  publishDictationStatus({ sessionId: sid, uploadId, phase: "uploading", uploaded: 0, total: 1 });
  const reg = await fetch(`/dictation/upload`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", "Idempotency-Key": args.uploadId, ...authHeaders() },
    body: JSON.stringify({ sessionId: args.sessionId, baselineBufferBytes: args.baselineBufferBytes }),
    signal,
  });
  if (!reg.ok) return failed(`Couldn't start the upload (server said ${reg.status}).`);
  const regBody = (await reg.json().catch(() => ({}))) as { upload_id?: string };
  const id = encodeURIComponent(regBody.upload_id ?? args.uploadId);

  // 2. Upload chunks with per-chunk retry, so a dropped chunk on a bad connection resumes at that
  //    chunk instead of restarting the whole clip.
  const bytes = new Uint8Array(await args.audio.arrayBuffer());
  const ranges = planUploadChunks(bytes.length, MAX_UPLOAD_CHUNK_BYTES);
  publishDictationStatus({ sessionId: sid, uploadId, phase: "uploading", uploaded: 0, total: ranges.length });
  let uploaded = 0;
  for (const range of ranges) {
    const part = bytes.subarray(range.start, range.end);
    const sha = await sha256Hex(part);
    let ok = false;
    let lastErr = "";
    for (let attempt = 0; attempt < CHUNK_RETRIES && !ok; attempt++) {
      try {
        const put = await fetch(`/dictation/${id}/chunk/${range.index}`, {
          method: "PUT",
          headers: { "Content-Type": "application/octet-stream", "X-Chunk-Sha256": sha, ...authHeaders() },
          body: part,
          signal,
        });
        ok = put.ok;
        if (!ok) lastErr = `chunk ${range.index}: ${put.status}`;
      } catch (e) {
        lastErr = e instanceof Error ? e.message : String(e);
      }
      if (!ok && attempt < CHUNK_RETRIES - 1) await uploadBackoff(400 * (attempt + 1), signal);
    }
    if (!ok) return failed(`Upload interrupted (${lastErr}).`);
    uploaded += 1;
    publishDictationStatus({ sessionId: sid, uploadId, phase: "uploading", uploaded, total: ranges.length });
  }

  // 3. Complete: the server assembles, transcribes, and injects the turn.
  const completeBody = {
    sessionId: args.sessionId,
    totalChunks: ranges.length,
    mime: args.audio.type || "audio/webm",
    ext: extForMime(args.audio.type),
    before: args.before,
    after: args.after,
    prefix: args.prefix,
    baselineBufferBytes: args.baselineBufferBytes,
    resumed: args.resumed,
  };
  const complete = (): Promise<Response> =>
    fetch(`/dictation/${id}/complete`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
      body: JSON.stringify(completeBody),
      signal,
    });

  // The server now assembles, transcribes, and injects inside this one request, so from the client's
  // side "complete in flight" is the transcribing phase.
  publishDictationStatus({ sessionId: sid, uploadId, phase: "transcribing" });
  let comp = await complete();
  if (comp.status === 409) {
    // Some chunks did not land; re-send exactly those, then complete once more.
    const body = (await comp.json().catch(() => ({}))) as { missing?: number[] };
    for (const i of body.missing ?? []) {
      const r = ranges[i];
      if (!r) continue;
      const part = bytes.subarray(r.start, r.end);
      await fetch(`/dictation/${id}/chunk/${i}`, {
        method: "PUT",
        headers: { "Content-Type": "application/octet-stream", "X-Chunk-Sha256": await sha256Hex(part), ...authHeaders() },
        body: part,
        signal,
      });
    }
    comp = await complete();
  }

  if (comp.status === 402) {
    // Out of credits is a hard failure a plain retry will not fix - mark it non-retryable so the strip
    // offers "Add credits" rather than a pointless Retry, then throw so the caller's credits UI fires.
    publishDictationStatus({ sessionId: sid, uploadId, phase: "failed", retryable: false, error: "Out of transcription credits." });
    throw creditsErrorFrom(await comp.json().catch(() => ({})));
  }
  const body = (await comp.json().catch(() => ({}))) as { submitted?: boolean; movedOn?: boolean; transcript?: string; error?: string };
  if (!comp.ok) {
    // The transcription-provider failures (the #1139 502/504 wrapping upstream_timeout) land here. The
    // audio is saved durably, so this is a HELD-and-will-retry state, not a loss - say so, and keep it
    // sticky on screen and on the roster until it retries or the user dismisses it.
    return failed(providerFailureMessage(body.error, comp.status));
  }
  publishDictationStatus({ sessionId: sid, uploadId, phase: "done" });
  return { terminal: true, submitted: Boolean(body.submitted), movedOn: Boolean(body.movedOn), transcript: body.transcript ?? "" };
}

// Turn a raw transcription-provider error into a short, honest, human sentence for the status strip.
// The audio is durable at this point, so every one of these is a "held, will retry" state.
function providerFailureMessage(serverError: string | undefined, status: number): string {
  const raw = (serverError ?? "").toLowerCase();
  if (raw.includes("upstream_timeout") || raw.includes("did not respond") || status === 504)
    return "The transcription service timed out. Your recording is saved and will retry.";
  if (raw.includes("upstream_unavailable") || status === 503)
    return "The transcription service is temporarily unavailable. Your recording is saved and will retry.";
  return `Transcription didn't go through (${serverError ?? status}). Your recording is saved and will retry.`;
}

function extForMime(mime: string | undefined): string {
  const m = (mime ?? "").toLowerCase();
  if (m.includes("webm")) return "webm";
  if (m.includes("ogg")) return "ogg";
  if (m.includes("mp4") || m.includes("m4a") || m.includes("aac")) return "m4a";
  if (m.includes("mpeg") || m.includes("mp3")) return "mp3";
  if (m.includes("wav")) return "wav";
  return "webm";
}

function uploadBackoff(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    const t = setTimeout(resolve, ms);
    signal?.addEventListener("abort", () => { clearTimeout(t); reject(new Error("aborted")); }, { once: true });
  });
}

// ===== Wingman Voice mode (issue #850): the mobile hands-free narration loop =====
// The whole backend is already built and proven on the desktop Cockpit voice tab and the native
// phone app (the explain/voice/ready/menu endpoints below). These typed helpers are the mobile
// PWA's same-origin door to them, each carrying the same Bearer the rest of the client uses so the
// Voice screen works with global Gateway auth on or off. The Wingman is READ-ONLY: explain and the
// voice reads never type into the session; only menu-press / sendPrompt reach the agent, through
// the existing single write chokepoint.
//
// These response shapes are returned by the Gateway via Results.Json WITHOUT a [Produces]
// annotation, so they are not in the generated OpenAPI schema; they are read with narrow local
// types for exactly the fields the Voice screen consumes (the same pattern getDirectors uses).

/** Read-only narration of the latest turn (POST /sessions/{sid}/wingman/explain). Also MARKS the
 *  session as a voice session, so the Gateway's turn-end watcher re-narrates every following turn. */
export interface WingmanExplain {
  reply: string;
  spoken: string;
  replySeconds: number;
  /** True for a fresh/text-only session with nothing to summarize yet (no audio was produced). */
  nothingYet: boolean;
}

/** The precomputed spoken summary + readiness metadata for a session (GET .../wingman/voice). */
export interface WingmanVoice {
  ready: boolean;
  spoken: string;
  reply: string;
  /** ISO-8601 stamp of when this clip was generated; it is the clip's identity (a new turn -> a
   *  new stamp), so the phone uses it to tell a fresh narration from the one it already holds. */
  generatedAt: string;
}

/** One option of a waiting on-screen choice (GET .../wingman/menu). */
export interface WingmanMenuOption {
  /** Short human label, e.g. "1. Yes". */
  key: string;
  /** The exact keystrokes that pick this option. For a single-select menu this includes the
   *  confirm (e.g. "1\r"); for a multiple-select checklist it is just the toggle (e.g. "1"). */
  send: string;
  /** The consequence/risk of choosing this option (<= 18 words). */
  note: string;
  /** True on at most one option - the Wingman's recommended/default pick. */
  recommended: boolean;
}

/** A detected waiting choice and its options (GET .../wingman/menu). */
export interface WingmanMenu {
  isMenu: boolean;
  question: string;
  spoken: string;
  /** "single" to pick exactly one; "multiple" for a pick-any checklist completed by submit. */
  selectionMode: "single" | "multiple";
  /** The keystroke that completes a multiple-select menu (e.g. "\r"); empty for single-select. */
  submit: string;
  options: WingmanMenuOption[];
}

// POST /sessions/{sid}/wingman/explain - mark the session as a voice session AND read its latest
// turn back as a spoken summary, without sending anything into the session. This is what entering
// voice mode fires; the Gateway caches the spoken text + audio so the phone can then download it.
export async function markVoiceAndExplain(sessionId: string, signal?: AbortSignal): Promise<WingmanExplain> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/explain`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    // Switching a session to voice mode ran into out-of-credits (issue #942): the shared notice.
    if (res.status === 402) throw creditsErrorFrom(await res.json().catch(() => ({})));
    throw new GatewayError(res.status, `POST wingman/explain failed: ${res.status}`);
  }
  const body = (await res.json()) as Partial<WingmanExplain>;
  return {
    reply: body.reply ?? "",
    spoken: body.spoken ?? "",
    replySeconds: Number(body.replySeconds ?? 0),
    nothingYet: Boolean(body.nothingYet),
  };
}

// GET /sessions/{sid}/wingman/voice - the precomputed spoken summary + readiness for the session's
// current (latest) narration. ready=false means the Gateway has nothing cached yet.
export async function getWingmanVoice(sessionId: string, signal?: AbortSignal): Promise<WingmanVoice> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/voice`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET wingman/voice failed: ${res.status}`);
  }
  const body = (await res.json()) as Partial<WingmanVoice>;
  return {
    ready: Boolean(body.ready),
    spoken: body.spoken ?? "",
    reply: body.reply ?? "",
    generatedAt: body.generatedAt ?? "",
  };
}

// GET /sessions/{sid}/wingman/voice/audio - the cached MP3 bytes for the session's current clip.
// Returned as an ArrayBuffer so the phone-side download gate (voice/clips.ts) can store it locally
// and expose a "phone-ready" state distinct from "gateway-ready". Binary, never base64 over the wire.
export async function fetchWingmanVoiceAudio(sessionId: string, signal?: AbortSignal): Promise<ArrayBuffer> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/voice/audio`, {
    method: "GET",
    headers: { Accept: "audio/mpeg", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    // Narration audio unavailable because of credits (issue #942): a 402 body is JSON even here.
    if (res.status === 402) throw creditsErrorFrom(await res.json().catch(() => ({})));
    throw new GatewayError(res.status, `GET wingman/voice/audio failed: ${res.status}`);
  }
  return res.arrayBuffer();
}

// GET /sessions/{sid}/wingman/menu - is the agent showing an on-screen menu right now, and what are
// its options? The Voice screen reads this to render pressable option buttons. The Gateway returns
// isMenu=false cheaply (no model call) when the terminal does not look like a menu.
export async function getWingmanMenu(sessionId: string, signal?: AbortSignal): Promise<WingmanMenu> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/menu`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET wingman/menu failed: ${res.status}`);
  }
  const body = (await res.json()) as Partial<WingmanMenu> & { options?: Partial<WingmanMenuOption>[] };
  return {
    isMenu: Boolean(body.isMenu),
    question: body.question ?? "",
    spoken: body.spoken ?? "",
    selectionMode: body.selectionMode === "multiple" ? "multiple" : "single",
    submit: body.submit ?? "",
    options: (body.options ?? []).map((o) => ({
      key: o.key ?? "",
      send: o.send ?? "",
      note: o.note ?? "",
      recommended: Boolean(o.recommended),
    })),
  };
}

// POST /sessions/{sid}/wingman/menu-press - answer a waiting choice from the phone by sending the
// exact keystrokes. This is the single write chokepoint for a choice (the Wingman charter stays
// read-only). For a single-select menu, `send` is one option's full keystroke and `submit` is
// omitted; for a multiple-select checklist, `send` is the concatenated toggle keystrokes of every
// chosen option and `submit` completes the selection.
export async function pressWingmanMenu(
  sessionId: string,
  send: string,
  submit?: string,
  signal?: AbortSignal,
): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const body: { send: string; submit?: string } = submit ? { send, submit } : { send };
  const res = await fetch(`/sessions/${sid}/wingman/menu-press`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST wingman/menu-press failed: ${res.status}`);
  }
}

// POST /sessions/{sid}/voice-mode { enabled } - the owning Director's authoritative voice flag. This
// is the SAME endpoint the native phone app drives (DirectorVoiceClient.SetVoiceModeAsync): enabled
// sets the session's mobile view mode to Voice, so SessionDto.VoiceMode flips true for every client
// (the roster shows it as a voice session and it persists across navigation); disabled leaves voice
// (view mode -> Text). It reaches the Director through the Gateway catch-all session proxy with the
// injected Bearer, exactly like sendPrompt/holdSession. Switching voice on calls this AND
// markVoiceAndExplain (which marks the Gateway's turn-end re-narration set and reads the first turn).
export async function setVoiceMode(sessionId: string, enabled: boolean, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/voice-mode`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ enabled }),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST voice-mode failed: ${res.status}`);
  }
}

// POST /sessions/{sid}/wingman/voice/stop - tell the Gateway to stop keeping voice for this session
// (issue #859). It unmarks the session as a voice session, so the Gateway stops spending the
// per-turn Opus translation + text-to-speech on it (the turn-end watcher and the background sweep
// both skip it once unmarked) and drops its cached clip. The counterpart to markVoiceAndExplain
// (which marks it on entry). "Turn voice off" calls this together with setVoiceMode(sid, false): the
// Director call flips the roster flag, this call stops the Gateway work. Gateway-side and read-only -
// it sends nothing into the session.
export async function stopWingmanVoice(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/voice/stop`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST wingman/voice/stop failed: ${res.status}`);
  }
}
