// Typed Gateway client. The TYPES come from the OpenAPI document the Gateway emits
// (src/api/schema.ts, generated by `npm run gen:api`), so the C# DTOs stay the single source
// of truth: a C# DTO change that is not reflected in a regenerated schema fails this build.
//
// The credential on every call is the PER-DEVICE KEY this browser obtained at enrollment
// (issue #908 for the phone, issue #1088 for the desktop Cockpit) - the one standing credential in
// the system. No token is injected into the page; the shell carries no secret until the person
// signs in on devthrottle.com and the device enrolls with the Gateway.
import type { components } from "./schema";
import type { SessionHistoryDto } from "../history/types";
import { planUploadChunks } from "./chunking";
import { getDeviceKey, clearDeviceKey } from "../auth/deviceKey";
import { publishDictationStatus } from "../dictation/status";

export type SessionDto = components["schemas"]["SessionDto"];

// Request bodies are typed from the generated OpenAPI schema (the C# DTOs stay the source of
// truth). The buffer/escape/interrupt/transcription responses are not declared in the schema (the
// Gateway returns them via Results.Json without a [Produces] annotation), so they are read with
// narrow local shapes for exactly the fields the mobile views consume.
type PromptRequest = components["schemas"]["PromptRequest"];
type NewSessionRequest = components["schemas"]["NewSessionRequest"];

// One machine (Director) in the fleet, projected from GET /directors. The response is not declared
// in the OpenAPI schema (the Gateway returns it via Results.Json without a [Produces] annotation),
// so it is read with this narrow local shape - the exact subset the add-session flow consumes,
// mirroring the Android phone/CcDirectorClient DirectorInfo.
export interface DirectorInfo {
  directorId: string;
  machineName: string;
  /** Best-effort version label for the picker subtitle. */
  version: string;
  /** When the Director process started (ISO 8601 UTC), or empty. Drives the picker "up <uptime> /
   *  started <when>" subtitle (issue #848); empty/unparseable degrades to last-seen only. */
  startedAt: string;
  /** When the Gateway last heard from this Director (ISO 8601), or empty. Used to default-select. */
  lastSeen: string;
  /** The Director's Control API endpoint, e.g. "http://127.0.0.1:7880" or a tailnet URL. Carries the
   *  PORT, which is what distinguishes several Directors (slots) on the SAME machine in the picker. */
  controlEndpoint: string;
}

/** GET /healthz - what the running Gateway reports about itself. Backs the mobile About screen. */
export interface GatewayHealth {
  status: string;
  directors: number;
  sessions: number;
  version: string;
  serverTime: string;
}

// One recently-used repository on a Director, projected from GET /directors/{id}/repos. Also not in
// the OpenAPI schema; read with this narrow local shape, mirroring the Android RepoInfo.
export interface RepoInfo {
  name: string;
  path: string;
  /** When a session last used this repo (ISO 8601), or empty. The list is sorted newest-used first. */
  lastUsed: string;
}

// The app's credential is the per-device key it obtained at enrollment (issue #908/#1088), read from
// the device-key store - NOT a token injected into the page (the shell carries no secret). Empty until
// this device has enrolled, in which case the caller (the auth gate) routes to the Sign in screen.
function gatewayToken(): string {
  return getDeviceKey();
}

// Exported so the dictation transcription calls (which post raw audio bytes and read a transcript)
// attach the same Bearer the rest of the client uses. Empty headers before enrollment; the app gates
// on the device key so no data call runs without one.
export function authHeaders(): HeadersInit {
  const token = gatewayToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

// Mirror the per-device key into the cc-gateway-token cookie (issue #817/#908). A browser WebSocket
// cannot set an Authorization header, so the live terminal stream (GET /sessions/{sid}/stream)
// authenticates via this cookie, which the same-origin handshake carries and the Gateway's
// AuthMiddleware accepts (HasValidToken checks the cookie against the shared token OR an active
// per-device key). The key is already in this origin's storage, so the cookie exposes nothing new; it
// is scoped to this origin. A no-op before enrollment (no key yet - the stream is never opened then).
export function ensureGatewayCookie(): void {
  const token = gatewayToken();
  if (!token) return;
  document.cookie = `cc-gateway-token=${encodeURIComponent(token)}; path=/; SameSite=Lax`;
}

// The redirect target when a credentialed call is rejected (401) mid-session is SHELL-AWARE, because
// the two shells that share this client re-gate through sign-in entries at different paths: the
// mobile PWA's enrollment screen lives at /m/signin, the desktop Cockpit's at /signin. Shared
// client-core must NOT hardcode either shell's route for the other (issue #1024), so the target is
// INJECTED per shell at startup via configureUnauthorizedRedirect. The resolver is given the current
// in-app location so a shell that carries the route forward (the desktop next=) can build a
// round-trip target.
export interface SignInLocation {
  pathname: string;
  search: string;
}
export type SignInRedirect = (current: SignInLocation) => string;

// The desktop Cockpit's sign-in redirect (issue #1088): re-gate through the Cockpit's own /signin
// route - the SAME shared client-core enrollment flow the phone uses - carrying the current route in
// next= so the browser lands back where it was once this device is enrolled again. This replaced the
// former /login token-wall re-gate (the raw-token wall is break-glass only, issue #1077): after a
// website revoke the desktop returns to the shared sign-in flow, never to login.html.
export function cockpitSignInRedirect(current: SignInLocation): string {
  return `/signin?next=${encodeURIComponent(current.pathname + current.search)}`;
}

// The mobile PWA's sign-in redirect: its own /m/signin enrollment screen, absolute under the /m
// basename so it works from any in-app route. This is what the mobile shell installs at startup, and it
// is the default so an unconfigured client-core still serves the shell that historically owned it.
export function mobileSignInRedirect(): string {
  return "/m/signin";
}

let signInRedirect: SignInRedirect = mobileSignInRedirect;

// Each shell installs its own sign-in redirect at startup (the mobile PWA -> mobileSignInRedirect, the
// desktop Cockpit -> cockpitSignInRedirect), so a mid-session 401 re-gates through the entry that shell
// actually uses instead of the mobile route baked into shared client-core (issue #1024).
export function configureUnauthorizedRedirect(redirect: SignInRedirect): void {
  signInRedirect = redirect;
}

// The configured sign-in target for the given current location. Exported so onUnauthorized has one
// place to resolve it and the shell-aware behavior is unit-testable without a DOM.
export function resolveSignInTarget(current: SignInLocation): string {
  return signInRedirect(current);
}

// Called when the Gateway answers 401 to a credentialed call: the device key was revoked (from the
// website's "Your devices") or is otherwise no longer valid. Forget it and send the user back to the
// shell's own Sign in entry, so a revoke on the account promptly ends access (the revoke round-trip,
// issue #908). A hard navigation (not the router) guarantees the whole app re-gates from a clean state.
function onUnauthorized(): void {
  clearDeviceKey();
  if (typeof window === "undefined") return;
  const target = resolveSignInTarget({
    pathname: window.location.pathname,
    search: window.location.search,
  });
  // Compare on the path only so a resolver that appends a query (the desktop next=) does not loop
  // when the browser is already sitting on the sign-in entry.
  const targetPath = target.split("?")[0];
  if (window.location.pathname !== targetPath) {
    window.location.assign(target);
  }
}

export class GatewayError extends Error {
  readonly status: number;
  constructor(status: number, message: string) {
    super(message);
    this.name = "GatewayError";
    this.status = status;
  }
}

// The shared "hosted AI is unavailable" body every money endpoint returns on HTTP 402 (issue #939/#941;
// consumed by mobile in #942): the single-source message + call-to-action. `text` is the message to show;
// `ctaUrl` deep-links to Billing.
export interface HostedAiUnavailable {
  state: string;      // "NeedsCredits" | "CapReached" | "NeedsKey"
  text: string;
  ctaLabel: string;
  ctaAction: string;  // "OpenBilling" | "OpenSettings"
  ctaUrl: string | null;
}

// A 402 from a hosted-AI call (out of credits / cap / no key). Its `message` IS the shared text, so any
// surface that already shows `err.message` displays the correct copy by construction; `info` carries the
// call-to-action for the app-level notice (issue #942).
export class CreditsError extends GatewayError {
  readonly info: HostedAiUnavailable;
  constructor(info: HostedAiUnavailable) {
    super(402, info.text || info.state || "Voice needs credit.");
    this.name = "CreditsError";
    this.info = info;
  }
}

// App-level subscription so ONE notice (with the "Add credits" button) shows wherever a 402 happens,
// without every surface widening its string error state. The client emits on every hosted-AI 402; the
// app renders a single CreditsNotice. Returns an unsubscribe function.
type CreditsListener = (info: HostedAiUnavailable) => void;
const creditsListeners = new Set<CreditsListener>();
export function onCreditsNeeded(fn: CreditsListener): () => void {
  creditsListeners.add(fn);
  return () => { creditsListeners.delete(fn); };
}

// Build a CreditsError from an already-parsed 402 body and notify the app-level notice. Defaults keep the
// message correct even if a field is missing. Call from the `!res.ok` branch of any hosted-AI call when
// `res.status === 402` (the body is already the shared shape from the Gateway).
export function creditsErrorFrom(body: unknown): CreditsError {
  const b = (body ?? {}) as Partial<HostedAiUnavailable> & { error?: string };
  const info: HostedAiUnavailable = {
    state: b.state ?? "NeedsCredits",
    text: b.text ?? b.error ?? "Voice needs credit. Add credits to turn it on.",
    ctaLabel: b.ctaLabel ?? "Add credits",
    ctaAction: b.ctaAction ?? "OpenBilling",
    ctaUrl: b.ctaUrl ?? null,
  };
  for (const fn of creditsListeners) { try { fn(info); } catch { /* a listener must never break the throw */ } }
  return new CreditsError(info);
}

// The single user-facing line for "the Gateway is unreachable", shared by every page that reads the
// Gateway on a poll (issue #1028). It implies the automatic retry those pages already perform, so the
// copy is truthful wherever it appears.
export const GATEWAY_UNREACHABLE_MESSAGE = "Can't reach the Gateway - retrying.";

// True when an error means the request never reached a healthy backend: the browser's bare fetch
// rejection when the Gateway is down (a TypeError, not a GatewayError), or a Gateway/proxy status
// that signals it could not reach the backend (Bad Gateway, Service Unavailable, Gateway Timeout, or
// a synthetic 0). These are the "unreachable" cases, distinct from a reachable Gateway that answered
// with an application error (400/404/409/500).
function isGatewayUnreachable(err: unknown): boolean {
  if (err instanceof GatewayError) {
    return err.status === 0 || err.status === 502 || err.status === 503 || err.status === 504;
  }
  return err instanceof Error;
}

// Map any error thrown by a Gateway read/write into ONE user-facing line, never leaking the internal
// "METHOD /path failed: NNN" diagnostic the client throws on a non-2xx, nor the browser's bare
// "Failed to fetch" when the backend is down (issue #1028). An unreachable Gateway collapses to the
// shared friendly, retry-implying line; a GatewayError that already carries human copy (a 401 re-auth
// prompt, a 402 credits notice) is returned verbatim; any other reachable-but-erroring status is
// reported by its number only, without the raw method and path.
export function gatewayErrorMessage(err: unknown): string {
  if (isGatewayUnreachable(err)) return GATEWAY_UNREACHABLE_MESSAGE;
  if (err instanceof CreditsError) return err.message;
  if (err instanceof GatewayError) {
    if (err.status === 401) return err.message;
    return `The Gateway rejected the request (error ${err.status}).`;
  }
  return GATEWAY_UNREACHABLE_MESSAGE;
}

type GatewayErrorBody = {
  error?: unknown;
  detail?: unknown;
  message?: unknown;
  code?: unknown;
};

function stringFromErrorBody(body: unknown): string | undefined {
  if (typeof body === "string") return body;
  if (!body || typeof body !== "object") return undefined;
  const b = body as GatewayErrorBody;
  if (typeof b.error === "string") return b.error;
  if (b.error && typeof b.error === "object") {
    const nested = b.error as GatewayErrorBody;
    const message = typeof nested.message === "string" ? nested.message : undefined;
    const code = typeof nested.code === "string" ? nested.code : undefined;
    return [message, code].filter(Boolean).join(" ") || undefined;
  }
  if (typeof b.detail === "string") return b.detail;
  if (typeof b.message === "string") return b.message;
  if (typeof b.code === "string") return b.code;
  return undefined;
}

async function readGatewayErrorBody(res: Response): Promise<string | undefined> {
  const text = await res.text().catch(() => "");
  if (!text.trim()) return undefined;
  try {
    return stringFromErrorBody(JSON.parse(text)) ?? text;
  } catch {
    return text;
  }
}

// GET /sessions - the fleet roster aggregator. Returns the same SessionDto shape the Cockpit
// Mobile page consumes. Throws GatewayError on a non-2xx so the caller surfaces it (no silent
// fallback). The request is same-origin against the Gateway front door.
export async function listSessions(signal?: AbortSignal): Promise<SessionDto[]> {
  const res = await fetch("/sessions", {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (res.status === 401) {
    // The device key was revoked (or is otherwise invalid): forget it and re-gate to Sign in. The
    // roster is the first credentialed call the app makes, so this is where a revoke surfaces.
    onUnauthorized();
    throw new GatewayError(res.status, "This device is no longer authorized. Please sign in again.");
  }
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /sessions failed: ${res.status}`);
  }
  return (await res.json()) as SessionDto[];
}

// GET /sessions/{sid}/history - the parsed, agent-agnostic conversation history for one session
// (issue #811). The Director's SessionHistoryEndpoint returns SessionHistoryDto; the Gateway
// forwards it verbatim through the catch-all /sessions/{sid}/{**rest} proxy with the injected
// Bearer (no backend change), exactly the way Terminal reaches /prompt. The shape is not declared
// in the OpenAPI schema (it rides the generic per-session proxy), so it is read with the narrow
// local SessionHistoryDto type. A 404 (old Director / unknown session) is surfaced as a
// GatewayError so the caller can treat it as "nothing yet" rather than a hard failure.
export async function getSessionHistory(
  sessionId: string,
  signal?: AbortSignal,
): Promise<SessionHistoryDto> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/history`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET history failed: ${res.status}`);
  }
  return (await res.json()) as SessionHistoryDto;
}

// Write text (or a raw key escape sequence) to the session's PTY. appendEnter=true submits a typed
// line (the Send button); appendEnter=false writes the bytes verbatim (Enter "\r", arrow keys
// ESC[A/B/C/D) so the session reacts as if the key were pressed at the terminal.
export async function sendPrompt(
  sessionId: string,
  text: string,
  appendEnter: boolean,
  signal?: AbortSignal,
): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const body: PromptRequest = { text, appendEnter };
  const res = await fetch(`/sessions/${sid}/prompt`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST prompt failed: ${res.status}`);
  }
}

// Soft-stop the current turn (the agent driver's Escape). POST /sessions/{sid}/escape.
export async function sendEscape(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/escape`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST escape failed: ${res.status}`);
  }
}

// Interrupt a running agent turn (Ctrl+C). POST /sessions/{sid}/interrupt.
export async function sendInterrupt(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/interrupt`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST interrupt failed: ${res.status}`);
  }
}

// Reset the conversation context in place (/clear for Claude, /new for pi) without ending the
// process. POST /sessions/{sid}/clear-context. Only meaningful for drivers that declare the
// ClearContext capability; the caller gates the button on SessionDto.driverCapabilities.
export async function sendClearContext(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/clear-context`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST clear-context failed: ${res.status}`);
  }
}

// Open the tool's in-terminal history / rewind picker (Claude's double-Esc). POST
// /sessions/{sid}/history-picker. Gated on the History capability - a visible-terminal feature.
export async function sendHistoryPicker(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/history-picker`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST history-picker failed: ${res.status}`);
  }
}

// ===== Prompt queue (issue #972): the composer's Queue and the queue panel verbs =====
// A faithful port of the Blazor Cockpit DirectorClient queue methods. Every verb returns the
// server's authoritative queue (the owning Director owns the ordered list), so the caller
// replaces its whole list from the response rather than mutating optimistically. All routes are
// root-relative to the Gateway, which forwards the session-scoped verb to the owning Director.

/** One queued prompt, as returned by GET /sessions/{sid}/queue on a Director. */
export interface QueueItem {
  id: string;
  text: string;
  /** ISO 8601 UTC when the item was queued. */
  createdAt: string;
}

// Read the response's { items } as the authoritative queue. Shared by every queue verb so the
// parse lives in one place; a non-2xx throws so the caller surfaces it (no silent empty queue).
async function readQueue(res: Response, label: string): Promise<QueueItem[]> {
  if (!res.ok) {
    throw new GatewayError(res.status, `${label} failed: ${res.status}`);
  }
  const body = (await res.json().catch(() => ({}))) as { items?: QueueItem[] };
  return body.items ?? [];
}

// GET /sessions/{sid}/queue - the session's current queued prompts, in order.
export async function getQueue(sessionId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/queue`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "GET queue");
}

// ===== Source control (issue #1266) =====

/** One changed file in a session's repository, as returned by GET /sessions/{sid}/git. */
export interface GitChangeEntry {
  /** Repository-relative path of the changed file. */
  path: string;
  /** One-letter git change kind: "M" modified, "A" added, "D" deleted, "R" renamed, "C" copied, "?" untracked. */
  changeKind: string;
}

/**
 * A read-only snapshot of a session repository's source-control state (GET /sessions/{sid}/git).
 * `status` is "ok" | "not_a_repo" | "git_failed"; on a non-ok status `error` carries the detail and
 * the change lists are empty. The lists are additive fields the read endpoint fills for the Source
 * Control tab.
 */
export interface GitSnapshot {
  branch: string;
  dirty: boolean;
  ahead: number;
  behind: number;
  lastCommit: string;
  status: string;
  error?: string | null;
  stagedChanges: GitChangeEntry[];
  unstagedChanges: GitChangeEntry[];
}

// GET /sessions/{sid}/git - the read-only source-control snapshot for a session's repository. A non-2xx
// throws so the caller surfaces it (no silent empty state); a non-ok `status` in the body is a normal
// result the caller renders ("not a git repository" / "git failed"), not an error.
export async function getGitStatus(sessionId: string, signal?: AbortSignal): Promise<GitSnapshot> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/git`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET git failed: ${res.status}`);
  }
  const body = (await res.json()) as GitSnapshot;
  return {
    ...body,
    stagedChanges: body.stagedChanges ?? [],
    unstagedChanges: body.unstagedChanges ?? [],
  };
}

// POST /sessions/{sid}/queue { text } - append a prompt to the queue; returns the new queue.
export async function enqueuePrompt(sessionId: string, text: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/queue`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ text }),
    signal,
  });
  return readQueue(res, "POST queue");
}

// DELETE /sessions/{sid}/queue/{itemId} - remove one item; returns the remaining queue.
export async function deleteQueueItem(sessionId: string, itemId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}`, {
    method: "DELETE",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "DELETE queue item");
}

// POST /sessions/{sid}/queue/{itemId}/send - submit one queued item now; returns the remaining queue.
export async function sendQueueItem(sessionId: string, itemId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}/send`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "POST queue send");
}

// PATCH /sessions/{sid}/queue/{itemId} { text } - edit one item's text; returns the updated queue.
export async function editQueueItem(sessionId: string, itemId: string, text: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ text }),
    signal,
  });
  return readQueue(res, "PATCH queue item");
}

// POST /sessions/{sid}/queue/{itemId}/move-up - move one item earlier; returns the reordered queue.
export async function moveQueueItemUp(sessionId: string, itemId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}/move-up`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "POST queue move-up");
}

// POST /sessions/{sid}/queue/{itemId}/move-down - move one item later; returns the reordered queue.
export async function moveQueueItemDown(sessionId: string, itemId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const id = encodeURIComponent(itemId);
  const res = await fetch(`/sessions/${sid}/queue/${id}/move-down`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "POST queue move-down");
}

// DELETE /sessions/{sid}/queue - clear the whole queue; returns the (empty) queue.
export async function clearQueue(sessionId: string, signal?: AbortSignal): Promise<QueueItem[]> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/queue`, {
    method: "DELETE",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  return readQueue(res, "DELETE queue");
}

// ===== Screenshots gallery (issue #972): the captured-screenshots folder on the owning Director =====
// A faithful port of the Blazor DirectorClient screenshots methods. The folder is per-machine on the
// Director, but the Cockpit always asks in the context of the selected session, so the session id is
// the routing key and the Gateway forwards to the owning Director's machine-wide folder. The image
// BYTES are loaded by the browser same-origin through the Gateway's per-session proxy
// (screenshotFileUrl), so no absolute Director address ever reaches the page (issue #317 / #967).

/** One screenshot on a Director's machine. The Director pre-formats timeLabel so every surface
 *  shows the same label without re-deriving it. */
export interface ScreenshotInfo {
  fileName: string;
  /** Absolute on-disk path on the Director's machine, injected into the composer so the owning
   *  agent can read the image directly (no upload). */
  path: string;
  timeLabel: string;
  lastWriteUtc: string;
  sizeBytes: number;
}

/** GET /sessions/{sid}/screenshots: the resolved folder + its newest image files. */
export interface ScreenshotsResult {
  directory: string;
  /** Full folder count regardless of any count cap; 0 on old Directors (treat items.length as total). */
  total: number;
  items: ScreenshotInfo[];
}

// The same-origin URL for a screenshot's bytes, used as the thumbnail <img src> and the "view
// full size" link. Root-relative to the Gateway (never a Director address), so a Director that
// advertises only a loopback endpoint still renders correctly for a remote browser (issue #317).
export function screenshotFileUrl(sessionId: string, fileName: string): string {
  const sid = encodeURIComponent(sessionId);
  return `/sessions/${sid}/screenshots/file?name=${encodeURIComponent(fileName)}`;
}

// ===== Local Files (remote file viewer): any local file on the owning Director's disk =====
// Same request shape as the screenshot bytes above, generalized from "one screenshot" to "any file
// by absolute path". The client viewing a session always has the session id, so it asks the Gateway
// same-origin at /sessions/{sid}/file?path=... ; the Gateway's per-session catch-all resolves the
// owning Director and forwards the request there, and the Director streams the bytes off its own
// disk. The session id is purely the routing vehicle that reaches the right machine (the path is
// always a path on that machine), not a sandbox. Root-relative to the Gateway, so a browser <img>
// or <iframe> src carries the cc-gateway-token cookie exactly as the screenshot viewer does.

/** The same-origin URL for a local file's bytes on the owning Director, used as an <img>/<iframe>
 *  src and as the target of a Download link. `path` is an absolute path on the session's machine. */
export function sessionFileUrl(sessionId: string, path: string): string {
  const sid = encodeURIComponent(sessionId);
  return `/sessions/${sid}/file?path=${encodeURIComponent(path)}`;
}

// Fetch a local file's TEXT content through the Gateway (for the Markdown and text/code viewers,
// which need the string, not an <img>/<iframe> src). A non-OK response is thrown as a GatewayError
// so the viewer can show the real reason - 404 for a missing file, 503 for an offline Director -
// never a silent blank.
export async function fetchSessionFileText(sessionId: string, path: string, signal?: AbortSignal): Promise<string> {
  const res = await fetch(sessionFileUrl(sessionId, path), {
    method: "GET",
    headers: { ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET file failed: ${res.status}`);
  }
  return res.text();
}

// The on-disk SIZE of a file on the owning Director, for the download panel's "name - size" display
// (Local Files, Phase 4). We do NOT download the file to weigh it: a Range: bytes=0-0 request makes the
// Director - which already serves this route with enableRangeProcessing on - answer 206 Partial Content
// with a Content-Range header ("bytes 0-0/<total>") whose total is the full size, transferring a single
// byte. This reuses the existing range support and needs no new server or Gateway route (the per-session
// catch-all proxy forwards any verb/headers unchanged). A missing file or offline machine is thrown as a
// GatewayError (404 / 503) so the panel can fail loud. When the total cannot be read - an old or odd
// server that ignored the range and returned 200 - null is returned and the caller shows the name and
// Download with NO guessed size (the brief's "no fake size" rule; no fallback programming).
export async function fetchSessionFileSize(sessionId: string, path: string, signal?: AbortSignal): Promise<number | null> {
  const res = await fetch(sessionFileUrl(sessionId, path), {
    method: "GET",
    headers: { ...authHeaders(), Range: "bytes=0-0" },
    signal,
  });
  // 206 (range honored) and 200 (range ignored, full body) are both "ok"; anything else is a real error.
  if (!res.ok) {
    throw new GatewayError(res.status, `GET file size failed: ${res.status}`);
  }
  // We never read the body - drop it so a 200 (full-file) response does not stream needlessly.
  void res.body?.cancel();
  const contentRange = res.headers.get("Content-Range");
  if (contentRange) {
    // "bytes 0-0/<total>" - the number after the last slash is the full file size.
    const slash = contentRange.lastIndexOf("/");
    if (slash >= 0) {
      const total = Number(contentRange.slice(slash + 1).trim());
      if (Number.isFinite(total) && total >= 0) return total;
    }
  }
  return null;
}

// GET /sessions/{sid}/screenshots[?count=N] - the newest screenshots' metadata (not the bytes).
// count <= 0 fetches everything (the folder can hold thousands, so callers pass a cap). A 503 means
// the owning Director is offline (the Gateway could not reach it for this leg, issue #412); it is
// surfaced as a GatewayError so the caller can show a graceful "Director offline" state + Retry.
export async function getScreenshots(sessionId: string, count = 0, signal?: AbortSignal): Promise<ScreenshotsResult> {
  const sid = encodeURIComponent(sessionId);
  const path = count > 0 ? `/sessions/${sid}/screenshots?count=${count}` : `/sessions/${sid}/screenshots`;
  const res = await fetch(path, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET screenshots failed: ${res.status}`);
  }
  const body = (await res.json().catch(() => ({}))) as Partial<ScreenshotsResult>;
  return {
    directory: body.directory ?? "",
    total: Number(body.total ?? 0),
    items: body.items ?? [],
  };
}

// DELETE /sessions/{sid}/screenshots/file?name=... - delete one screenshot file from the Director's disk.
export async function deleteScreenshot(sessionId: string, fileName: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/screenshots/file?name=${encodeURIComponent(fileName)}`, {
    method: "DELETE",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `DELETE screenshot failed: ${res.status}`);
  }
}

// POST /sessions/{sid}/upload-image (multipart, field "file") - forward a device-local image to the
// owning Director, which saves it to its Screenshots folder and returns the absolute on-disk path.
// The caller inserts that path into the composer so the agent can read the image directly; the
// upload endpoint itself injects nothing into the session.
export async function uploadImage(sessionId: string, file: File, signal?: AbortSignal): Promise<string> {
  const sid = encodeURIComponent(sessionId);
  const form = new FormData();
  form.append("file", file, file.name);
  const res = await fetch(`/sessions/${sid}/upload-image`, {
    method: "POST",
    headers: { ...authHeaders() },
    body: form,
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST upload-image failed: ${res.status}`);
  }
  const body = (await res.json().catch(() => ({}))) as { path?: string };
  return body.path ?? "";
}

// GET /sessions/{sid}/handover (issue #1214): the desktop app's "Handover info" identity block for a
// session - what a person or another agent needs to locate the session and talk to it. Mirrors the
// desktop "Copy Handover Info" block, minus the Director's Control API endpoint (the browser talks only
// to the Gateway and never learns a Director address). Not declared in the generated OpenAPI schema
// (the Gateway returns it via Results.Json without a [Produces] annotation), so it is read with this
// narrow local shape - the exact subset the Cockpit Handover info view renders. The C# source of truth
// is CcDirector.Gateway.Contracts.HandoverInfoDto.
export interface SessionHandover {
  sessionId: string;
  displayName: string;
  repoPath: string;
  directorId: string;
  machineName: string;
  version: string;
}

// A non-2xx is surfaced as a GatewayError so the caller shows a visible error (never a silent empty
// panel): 404 when the session is unknown to every Director, 502 when the owning Director is offline.
export async function getHandover(sessionId: string, signal?: AbortSignal): Promise<SessionHandover> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/handover`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET handover failed: ${res.status}`);
  }
  const body = (await res.json().catch(() => ({}))) as Partial<SessionHandover>;
  return {
    sessionId: body.sessionId ?? "",
    displayName: body.displayName ?? "",
    repoPath: body.repoPath ?? "",
    directorId: body.directorId ?? "",
    machineName: body.machineName ?? "",
    version: body.version ?? "",
  };
}

// ===== Session management (issue #812): the add-session flow + Hold/Resume + Remove =====
// A faithful 1:1 of the Android (MAUI) phone/CcDirectorClient "+ New session" flow and the
// owner's Hold/Remove decision. Every call carries the same Bearer the rest of the client uses, so
// the whole flow works with global Gateway auth on or off.

// GET /healthz - the running Gateway's own status and version. No auth needed. Backs the mobile
// About screen so the user can confirm which build they are on.
export async function getGatewayHealth(signal?: AbortSignal): Promise<GatewayHealth> {
  const res = await fetch("/healthz", {
    method: "GET",
    headers: { Accept: "application/json" },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /healthz failed: ${res.status}`);
  }
  return (await res.json()) as GatewayHealth;
}

// GET /directors - the fleet's machines (Directors). Sorted most-recently-seen first so the picker
// can default-select the top one (matching FleetParser.ParseDirectors), tie-broken by machine name.
// Entries with no directorId are dropped (they cannot be addressed). Throws GatewayError on non-2xx
// so the picker shows the real reason instead of a silently empty list.
export async function getDirectors(signal?: AbortSignal): Promise<DirectorInfo[]> {
  const res = await fetch("/directors", {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /directors failed: ${res.status}`);
  }
  const raw = (await res.json()) as Array<Record<string, unknown>>;
  const list: DirectorInfo[] = raw
    .map((d) => ({
      directorId: String(d.directorId ?? ""),
      machineName: String(d.machineName ?? ""),
      version: String(d.version ?? ""),
      startedAt: String(d.startedAt ?? ""),
      lastSeen: String(d.lastSeen ?? ""),
      controlEndpoint: String(d.controlEndpoint ?? ""),
    }))
    .filter((d) => d.directorId.length > 0);
  list.sort((a, b) => {
    const bySeen = b.lastSeen.localeCompare(a.lastSeen); // newest-seen first (ISO 8601 sorts lexically)
    if (bySeen !== 0) return bySeen;
    return a.machineName.localeCompare(b.machineName);
  });
  return list;
}

// GET /directors/{id}/repos - a machine's recently-used repositories, sorted newest-used first
// (the server already sorts this way; we re-sort so a mixed body is still correct, matching
// FleetParser.ParseRepos). Entries with no path are dropped. Throws GatewayError on non-2xx.
export async function getRepos(directorId: string, signal?: AbortSignal): Promise<RepoInfo[]> {
  const id = encodeURIComponent(directorId);
  const res = await fetch(`/directors/${id}/repos`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /directors/${directorId}/repos failed: ${res.status}`);
  }
  const raw = (await res.json()) as Array<Record<string, unknown>>;
  const list: RepoInfo[] = raw
    .map((r) => ({
      name: String(r.name ?? ""),
      path: String(r.path ?? ""),
      lastUsed: String(r.lastUsed ?? ""),
    }))
    .filter((r) => r.path.length > 0);
  list.sort((a, b) => b.lastUsed.localeCompare(a.lastUsed)); // newest-used first
  return list;
}

// POST /directors/{id}/sessions - create a new session in repoPath. Agent is hardcoded "ClaudeCode"
// and wingmanEnabled=false, type omitted, exactly like the Android NewSessionPanel
// (FleetParser.BuildCreateBody). Returns the created SessionDto so the caller can open it. The
// Gateway answers 201 on success; throws GatewayError on non-2xx with the server's reason.
//
// launchArgs is the exact command-line argument string the Director passes to the agent (for example
// "--model opus --dangerously-skip-permissions"). Session launch applies no defaults, so a session
// created with no launchArgs comes up on the default model and blocked on a permission prompt - the
// caller decides. An empty or whitespace-only launchArgs sends no "args" at all, matching the
// historic behavior; callers that do not care (the mobile NewSession flow) simply omit it.
export async function createSession(
  directorId: string,
  repoPath: string,
  launchArgs?: string | null,
  signal?: AbortSignal,
): Promise<SessionDto> {
  const id = encodeURIComponent(directorId);
  const body: NewSessionRequest = { repoPath: repoPath.trim(), agent: "ClaudeCode", wingmanEnabled: false };
  const trimmedArgs = (launchArgs ?? "").trim();
  if (trimmedArgs.length > 0) body.args = trimmedArgs;
  const res = await fetch(`/directors/${id}/sessions`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok) {
    let detail = `${res.status}`;
    try {
      const err = (await res.json()) as { detail?: string; error?: string };
      detail = err.detail ?? err.error ?? detail;
    } catch {
      /* non-JSON error body - keep the status code */
    }
    throw new GatewayError(res.status, `Create session failed: ${detail}`);
  }
  return (await res.json()) as SessionDto;
}

// POST /sessions/{sid}/hold - toggle the session's on-hold state. The desired state is sent
// explicitly ({ onHold }) so the call is idempotent; the Director echoes the applied { onHold }.
// Reaches the Director through the Gateway catch-all session proxy with the injected Bearer.
export async function holdSession(
  sessionId: string,
  onHold: boolean,
  signal?: AbortSignal,
): Promise<boolean> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/hold`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ onHold }),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST hold failed: ${res.status}`);
  }
  const result = (await res.json().catch(() => ({}))) as { onHold?: boolean };
  return result.onHold ?? onHold;
}

// POST /sessions/{sid}/transcribing - mark or clear this session as transcribing a dictated
// utterance in the background (the phone hit Send in the Speak dialog and released the screen). This
// is a Gateway-owned transient flag ONLY - it is not forwarded to the Director; it drives the orange
// "Transcribing..." roster color so nobody else starts using the session while its audio is being
// uploaded and transcribed. Sent true the instant Send is pressed and false once the background
// upload/transcribe/submit finishes or fails. Reaches a Gateway-native literal route (no Director
// hop) with the injected Bearer.
export async function setTranscribing(
  sessionId: string,
  transcribing: boolean,
  signal?: AbortSignal,
): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/transcribing`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ transcribing }),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST transcribing failed: ${res.status}`);
  }
}

// DELETE /sessions/{sid} - kill the agent process and remove the session from the roster (the
// Android kill/remove semantics, gated behind a confirmation per the owner's #545 request). Reaches
// the Director through the Gateway catch-all session proxy with the injected Bearer.
export async function killSession(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}`, {
    method: "DELETE",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `DELETE session failed: ${res.status}`);
  }
}

// Dictation transcription (issue #817). Speech-to-text for the Speak dialog goes through the
// EXISTING resilient batch-upload flow the Gateway exposes for the phone (register -> chunk ->
// complete): the same record-then-ship-then-transcribe shape the native mobile app uses, resumable
// on a poor phone network because each landed chunk stays landed. The Gateway transcribes the
// reassembled clip with the hosted transcription mode the machine is set to and returns the transcript already run through
// the SAME dictionary-correction engine every surface uses - so we prefer/return that cleaned text.
//
// The Director's own /voice/utterance flow is NOT proxied through the Gateway; this /wingman/
// utterance flow is the Gateway-native equivalent and is reachable by the mobile app same-origin
// with the Bearer, so no backend change is needed.
// The optional client-measured capture-health sent with the complete call (issue #863), so the
// Gateway can persist the audio-loss deficit (recording wall-clock vs decoded audio duration) into
// the same dictation session log every other surface writes. Diagnostics only - omitting it changes
// nothing about the transcription.
export interface UtteranceCaptureHealth {
  recordedMs: number;
  decodedSeconds: number;
  sourceBytes: number;
}

// The largest a single upload chunk may be. A long recording is uploaded as several chunks of at
// most this size so no single request body exceeds the Gateway limit (Kestrel's default is roughly
// thirty megabytes; a twenty-minute clip is larger). This is independent of how the server later
// splits the reassembled clip into bounded transcription requests - it only bounds the upload hop.
const MAX_UPLOAD_CHUNK_BYTES = 5_000_000;

export async function transcribeUtterance(
  wav: Blob,
  health?: UtteranceCaptureHealth,
  signal?: AbortSignal,
  onProgress?: (uploadedChunks: number, totalChunks: number) => void,
): Promise<string> {
  // 1. Register the upload (mints an id the chunk + complete calls address).
  const reg = await fetch(`/wingman/utterance/upload`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!reg.ok) {
    const error = await readGatewayErrorBody(reg);
    throw new GatewayError(reg.status, transcriptionFailureMessage(error, reg.status));
  }
  const regBody = (await reg.json()) as { upload_id?: string };
  const uploadId = regBody.upload_id;
  if (!uploadId) {
    throw new GatewayError(reg.status, "transcription register returned no upload id");
  }

  // 2. Upload the WAV in bounded chunks so a long recording never exceeds the Gateway request-body
  //    limit. Each chunk carries its own SHA256, so the server rejects corruption and treats a
  //    retried chunk as a free no-op; the server reassembles the chunks in order before transcribing.
  const bytes = new Uint8Array(await wav.arrayBuffer());
  const id = encodeURIComponent(uploadId);
  const ranges = planUploadChunks(bytes.length, MAX_UPLOAD_CHUNK_BYTES);
  onProgress?.(0, ranges.length);
  for (const range of ranges) {
    const part = bytes.subarray(range.start, range.end);
    const sha = await sha256Hex(part);
    const put = await fetch(`/wingman/utterance/${id}/chunk/${range.index}`, {
      method: "PUT",
      headers: { "Content-Type": "application/octet-stream", "X-Chunk-Sha256": sha, ...authHeaders() },
      body: part,
      signal,
    });
    if (!put.ok) {
      const error = await readGatewayErrorBody(put);
      throw new GatewayError(put.status, transcriptionFailureMessage(error, put.status));
    }
    onProgress?.(range.index + 1, ranges.length);
  }

  // 3. Complete with the real chunk count -> the server reassembles all chunks, transcribes the clip
  //    (the pipeline itself splits the reassembled audio into bounded transcription requests), applies
  //    the dictionary correction, and returns the cleaned transcript.
  const comp = await fetch(`/wingman/utterance/${id}/complete`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({
      totalChunks: ranges.length,
      mime: "audio/wav",
      ext: "wav",
      clientRecordedMs: health?.recordedMs,
      clientDecodedSeconds: health?.decodedSeconds,
      clientSourceBytes: health?.sourceBytes,
    }),
    signal,
  });
  const compBody = (await comp.json().catch(() => ({}))) as { transcript?: string; error?: string };
  if (!comp.ok) {
    // Out of credits / cap (issue #942): a typed CreditsError carrying the shared message + call-to-action.
    if (comp.status === 402) throw creditsErrorFrom(compBody);
    throw new GatewayError(comp.status, transcriptionFailureMessage(compBody.error, comp.status));
  }
  return (compBody.transcript ?? "").trim();
}

// Hex SHA256 of the upload bytes via the Web Crypto API (available in any secure context, which a
// microphone-capable page already is).
async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// ===== Durable, server-owned dictation upload (issue #1006, strengthened for #1182) ==============
// Streams the raw recorded audio (already saved to the on-device durable store) to the Gateway in
// resumable, SHA-checked chunks; the Gateway then assembles, transcribes, and INJECTS the turn into
// the session itself. Once the server confirms it owns the turn, the local copy is deleted.
//
// This function is ONE self-contained delivery attempt. The retry CADENCE (hard for the first hour,
// then throttled, resumed on connectivity) lives in the background driver (dictation/backgroundSend.ts),
// which calls this repeatedly with the same uploadId. Because that uploadId is also the server's
// Idempotency-Key, every attempt is safe:
//   - Register is idempotent and RE-CREATES the staging folder even after the server's abandoned-upload
//     sweep, so a resume after an hour re-drives from the on-device copy (never a loss, criterion 9).
//   - The client discovers exactly which chunks the server still needs from complete's 409 { missing }
//     response, and uploads only those - a resume continues from the next missing chunk, never a restart
//     from zero (criterion 3).
//   - A dropped connection mid-chunk PAUSES the attempt (returns a held, retryable outcome); it does not
//     fail the whole clip. The next attempt resumes from the still-missing chunks.
//   - A complete that already succeeded server-side but whose response was lost is retried against the
//     Gateway's per-uploadId idempotency cache, which returns the SAME submitted outcome - so the turn is
//     injected exactly once and the #1135 duplicate pile-up cannot return (criterion 7).

/** The tight allow-list of GENUINELY PERMANENT, non-retryable transcription failures (issue #1184). A clip
 *  that hits one of these can never succeed AS-SENT, so it must stop the auto-retry loop and PARK rather
 *  than re-drive forever. EVERYTHING outside this list (network, provider 502/504, busy session, out of
 *  credits) stays retryable/held. Default is retryable; only these reasons are permanent.
 *   - "audio-too-large": the clip is over the provider's per-request byte cap and cannot be split as-sent.
 *   - "unsupported-format": the audio is a format the Gateway cannot decode or split. */
export type PermanentDictationReason = "audio-too-large" | "unsupported-format";

/** Outcome of one dictation delivery attempt.
 *  - `terminal` true: the server made a final decision (injected the turn, or deliberately dropped it as
 *    stale / empty) and the durable local copy can be deleted.
 *  - `permanent` true: a genuinely permanent, non-retryable failure (an allow-listed `permanentReason`,
 *    issue #1184). NOT terminal - the on-device copy is KEPT and the clip is PARKED (the auto-loop stops)
 *    until the user explicitly retries it; nothing was injected.
 *  - otherwise (`terminal` false, `permanent` falsey): nothing final happened; the copy is KEPT and the
 *    driver retries. `error` carries the honest "held, will keep trying" reason and `outOfCredits` flags
 *    the out-of-credits case so the driver can throttle and the app can show the Add-credits notice. */
export interface DictationSubmitResult {
  terminal: boolean;
  submitted: boolean;
  movedOn: boolean;
  /** True when the server returned an ABANDONED upload id (the dictation was given up server-side, issue
   *  #1183): terminal like a delivered turn, so the driver drops the on-device copy and does not re-drive,
   *  but nothing was injected. */
  abandoned?: boolean;
  /** True when the failure is genuinely permanent and non-retryable (issue #1184): the driver parks the
   *  clip (keeps the audio, stops the auto-loop) and offers an explicit user Retry. */
  permanent?: boolean;
  /** The allow-listed reason a permanent failure was parked (only set when `permanent` is true). */
  permanentReason?: PermanentDictationReason;
  transcript: string;
  error?: string;
  outOfCredits?: boolean;
}

export interface DictationUploadArgs {
  sessionId: string;
  /** Client-generated id (the durable record id); also the server upload id and Idempotency-Key. */
  uploadId: string;
  /** Raw recorded audio exactly as the microphone produced it. */
  audio: Blob;
  before: string;
  after: string;
  prefix: string;
  baselineBufferBytes: number;
  resumed: boolean;
}

/** The honest, plain-English line for a dictation whose delivery is paused because the connection
 *  dropped (mid-upload, or the Gateway is unreachable). The audio is safe on the device and the
 *  background driver keeps trying - never "was not transcribed", because it is held, not lost. */
export const DICTATION_HELD_NO_CONNECTION_MESSAGE =
  "No connection - your recording is saved and will keep trying.";

/** The held line when transcription credits ran out: kept, and it sends once credits are available. */
export const DICTATION_HELD_CREDITS_MESSAGE =
  "Out of transcription credits - your recording is saved and will send when credits are added.";

export async function uploadDictationToSession(
  args: DictationUploadArgs,
  signal?: AbortSignal,
): Promise<DictationSubmitResult> {
  // Live status is published for the mechanical steps (uploading / transcribing / done) here; the
  // driver owns the held-and-retrying status between attempts. A non-terminal outcome returns a held
  // result (terminal:false) with the honest reason, so the driver keeps the audio and retries.
  const sid = args.sessionId;
  const uploadId = args.uploadId;
  const held = (error: string, outOfCredits = false): DictationSubmitResult =>
    ({ terminal: false, submitted: false, movedOn: false, transcript: "", error, outOfCredits });
  const permanent = (reason: PermanentDictationReason): DictationSubmitResult =>
    ({ terminal: false, submitted: false, movedOn: false, transcript: "", permanent: true, permanentReason: reason });

  // 1. Register (idempotent by Idempotency-Key: re-opens the same staging on a resume, and RE-CREATES it
  //    if the server already swept the abandoned upload - so we always re-drive from the on-device copy).
  publishDictationStatus({ sessionId: sid, uploadId, phase: "uploading", uploaded: 0, total: 1 });
  let reg: Response;
  try {
    reg = await fetch(`/dictation/upload`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Accept: "application/json", "Idempotency-Key": args.uploadId, ...authHeaders() },
      body: JSON.stringify({ sessionId: args.sessionId, baselineBufferBytes: args.baselineBufferBytes }),
      signal,
    });
  } catch {
    return held(DICTATION_HELD_NO_CONNECTION_MESSAGE);
  }
  if (!reg.ok) return held(transcriptionFailureMessage(await readGatewayErrorBody(reg), reg.status, true));
  const regBody = (await reg.json().catch(() => ({}))) as {
    upload_id?: string;
    terminal?: boolean;
    submitted?: boolean;
    movedOn?: boolean;
    dropped?: boolean;
    transcript?: string;
  };
  const id = encodeURIComponent(regBody.upload_id ?? args.uploadId);

  // Durable de-dupe at register (issue #1183): the server already reached a terminal outcome for this
  // upload id (delivered or abandoned) - our earlier response was lost. Treat it exactly like a fresh
  // terminal outcome: acknowledge it (so the server can retire the tombstone) and return terminal so the
  // driver drops the on-device copy. No chunks are re-uploaded and nothing is injected a second time.
  if (regBody.terminal === true) {
    await ackDictation(id);
    return {
      terminal: true,
      submitted: Boolean(regBody.submitted),
      movedOn: Boolean(regBody.movedOn),
      abandoned: Boolean(regBody.dropped),
      transcript: regBody.transcript ?? "",
    };
  }

  // 2. Read the whole clip from the (already durable) on-device copy and plan its bounded chunks.
  const bytes = new Uint8Array(await args.audio.arrayBuffer());
  const ranges = planUploadChunks(bytes.length, MAX_UPLOAD_CHUNK_BYTES);
  const total = ranges.length;
  const completeBody = {
    sessionId: args.sessionId,
    totalChunks: total,
    mime: args.audio.type || "audio/webm",
    ext: extForMime(args.audio.type),
    before: args.before,
    after: args.after,
    prefix: args.prefix,
    baselineBufferBytes: args.baselineBufferBytes,
    resumed: args.resumed,
  };
  const complete = (): Promise<Response> =>
    fetch(`/dictation/${id}/complete`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
      body: JSON.stringify(completeBody),
      signal,
    });

  publishDictationStatus({ sessionId: sid, uploadId, phase: "uploading", uploaded: 0, total });

  // 3. Resume-from-missing loop. complete tells us (cheaply, before any transcription) which chunks the
  //    server still needs (409 { missing }); we upload exactly those from the on-device copy and complete
  //    again. On the first ever attempt nothing is up yet, so the first complete reports every index and
  //    we upload the whole clip; on a resume only the still-missing set is sent. Bounded so a server that
  //    keeps reporting the same chunk missing cannot spin forever - it becomes a held retry instead.
  let uploadedAllThisAttempt = false;
  const maxRounds = total + 2;
  for (let round = 0; round < maxRounds; round++) {
    // Only the complete AFTER all chunks are up does the real transcribe; show "transcribing" then.
    if (uploadedAllThisAttempt) publishDictationStatus({ sessionId: sid, uploadId, phase: "transcribing" });
    let comp: Response;
    try {
      comp = await complete();
    } catch {
      return held(DICTATION_HELD_NO_CONNECTION_MESSAGE);
    }

    if (comp.status === 409) {
      // Missing chunks: send exactly those, pausing (held) if the connection drops mid-chunk.
      const body = (await comp.json().catch(() => ({}))) as { missing?: number[] };
      const missing = (body.missing ?? []).filter((i) => ranges[i]);
      if (missing.length === 0) return held(transcriptionFailureMessage(undefined, 502, true));
      let uploaded = total - missing.length;
      publishDictationStatus({ sessionId: sid, uploadId, phase: "uploading", uploaded, total });
      for (const i of missing) {
        const r = ranges[i];
        const part = bytes.subarray(r.start, r.end);
        const sha = await sha256Hex(part);
        let put: Response;
        try {
          put = await fetch(`/dictation/${id}/chunk/${r.index}`, {
            method: "PUT",
            headers: { "Content-Type": "application/octet-stream", "X-Chunk-Sha256": sha, ...authHeaders() },
            body: part,
            signal,
          });
        } catch {
          // Connection dropped mid-chunk: pause here, keep every chunk that already landed, and let the
          // driver resume from the next missing chunk on the following attempt (criterion 3).
          return held(DICTATION_HELD_NO_CONNECTION_MESSAGE);
        }
        if (put.status === 404) {
          // The server swept this upload's staging between our register and this chunk. Re-register on the
          // next attempt (same Idempotency-Key) and re-drive from the on-device copy (criterion 9).
          return held(DICTATION_HELD_NO_CONNECTION_MESSAGE);
        }
        if (!put.ok) return held(transcriptionFailureMessage(await readGatewayErrorBody(put), put.status, true));
        uploaded += 1;
        publishDictationStatus({ sessionId: sid, uploadId, phase: "uploading", uploaded, total });
      }
      uploadedAllThisAttempt = true;
      continue;
    }

    if (comp.status === 402) {
      // Out of transcription credits: fire the app-level Add-credits notice, then keep the audio held so
      // it sends once credits return. A plain fast retry will not fix it, so the driver throttles this.
      creditsErrorFrom(await comp.json().catch(() => ({})));
      return held(DICTATION_HELD_CREDITS_MESSAGE, true);
    }

    const body = (await comp.json().catch(() => ({}))) as {
      submitted?: boolean; movedOn?: boolean; dropped?: boolean; transcript?: string; error?: string;
      permanent?: boolean; reason?: string;
    };

    // Genuinely permanent, non-retryable failure (issue #1184). The server (a later, coordinated step)
    // signals this on complete with { permanent: true, reason: <allow-listed> } - naturally an HTTP 422,
    // but we key off the typed body flag, not the status, so the server may pick any status. Only the
    // tight allow-list parks; a permanent flag with any other reason falls through to the retryable/held
    // path below, so the default stays retryable and the auto-loop is only ever stopped for the two
    // reasons that truly can never succeed as-sent.
    const reason = permanentReasonFrom(body.permanent, body.reason);
    if (reason !== null) return permanent(reason);

    if (!comp.ok) {
      // A reachable Gateway that answered with a server-side transcription fault (timeout / outage / no
      // key / session gone). Held, not lost - the honest "saved and will keep trying" copy.
      return held(transcriptionFailureMessage(body.error, comp.status, true));
    }

    // 200: the server made a final decision. submitted -> the turn was injected; movedOn -> the server
    // deliberately dropped a stale resumed clip; dropped -> the upload id was abandoned server-side (issue
    // #1183); neither -> a silent/empty clip with nothing to submit. All are terminal: the server owns the
    // outcome and holds a durable delivery record. Acknowledge it so the server can retire that tombstone
    // (best-effort, idempotent), then return terminal so the driver drops the durable local copy. The
    // background driver owns the terminal status (a "done" for a delivered turn, or a quiet clear).
    await ackDictation(id);
    return {
      terminal: true,
      submitted: Boolean(body.submitted),
      movedOn: Boolean(body.movedOn),
      abandoned: Boolean(body.dropped),
      transcript: body.transcript ?? "",
    };
  }

  // The server kept reporting missing chunks past the bounded rounds (a chunk that will not stick, e.g. a
  // persistent SHA rejection). Hold it - the driver retries from a clean register on the next attempt.
  return held(DICTATION_HELD_NO_CONNECTION_MESSAGE);
}

// Map a complete response's permanent-failure signal to an allow-listed reason, or null when it is not a
// permanent failure we recognize (issue #1184). Only "audio-too-large" and "unsupported-format" park; any
// other value - including a permanent flag with an unknown/blank reason - returns null so the clip stays
// on the default retryable/held path. This is the SINGLE gate that decides "park" versus "keep retrying",
// so the allow-list can never widen by accident.
function permanentReasonFrom(permanent: boolean | undefined, reason: string | undefined): PermanentDictationReason | null {
  if (permanent !== true) return null;
  if (reason === "audio-too-large" || reason === "unsupported-format") return reason;
  return null;
}

// Acknowledge a terminal dictation outcome so the Gateway can retire its durable de-dupe tombstone (issue
// #1183). Best-effort and idempotent, keyed by the (already-encoded) upload id: a lost ack simply leaves
// the tiny tombstone in place and a later re-complete returns the same outcome and re-acks. Never throws -
// a failed ack must never turn a delivered turn into an error.
async function ackDictation(encodedUploadId: string): Promise<void> {
  try {
    await fetch(`/dictation/${encodedUploadId}/ack`, {
      method: "POST",
      headers: { Accept: "application/json", ...authHeaders() },
    });
  } catch {
    /* best-effort: the tombstone persists and a later re-complete re-acks */
  }
}

// POST /dictation/{uploadId}/abandon (issue #1181, Task 5): the user gave up on this dictation. Tells the
// Gateway to mark the durable upload ABANDONED - discarding the staged audio and clearing the session lock.
// Unlike the fire-and-forget ack, this RETURNS whether the Gateway actually confirmed: the caller must know,
// because if the marker is not cleared the session would stay locked/orange forever. Returns false when the
// call could not reach a healthy Gateway, so the caller keeps the abandoning record and retries.
export async function abandonDictation(uploadId: string): Promise<boolean> {
  try {
    const res = await fetch(`/dictation/${encodeURIComponent(uploadId)}/abandon`, {
      method: "POST",
      headers: { Accept: "application/json", ...authHeaders() },
    });
    return res.ok;
  } catch {
    return false;
  }
}

// Turn a raw dictation-complete failure (any non-OK response from POST /dictation/{id}/complete) into a
// short, honest, plain-English sentence for the status strip and the error banner.
//
// This is the SINGLE place a dictation failure is turned into user-facing words. It never surfaces the
// raw server JSON/text at the user (the bug this fixes: a server-side outage used to reach the user as a
// raw "Transcription returned 502: {...}" dump), and every known server-side condition gets its own
// specific line so the user is told WHAT went wrong - a transcription-service outage, a busy session, no
// method configured - not merely that "transcription failed" (issue #1139 follow-up).
//
// `durable` frames the message for the caller's recovery model (issue #1182). The durable dictation path
// (uploadDictationToSession) keeps the audio and keeps retrying, so it passes durable=true and the copy
// says "saved and will keep trying" - never "was not transcribed", because it is held, not lost. The
// synchronous voice-narration path (transcribeUtterance) has no durable copy, so it uses the default
// (durable=false) and reports the fault plainly.
export function transcriptionFailureMessage(serverError: string | undefined, status: number, durable = false): string {
  const raw = (serverError ?? "").toLowerCase();

  if (status === 401)
    return "This device is no longer authorized. Please sign in again.";

  if (status === 403)
    return "This device is not allowed to use transcription on this Gateway.";

  // The session the dictation was headed for is gone (exited / not found).
  if (status === 404 || status === 410 || raw.includes("session not found") || raw.includes("session has exited"))
    return "That session is no longer available, so your dictation couldn't be delivered.";

  // No transcription method is configured on the Gateway (no key for the selected mode). A plain retry
  // will not fix it, so point at Settings rather than promising a quick retry.
  if (raw.includes("no key configured") || raw.includes("no key set"))
    return durable
      ? "No transcription method is set up. Open Settings > Transcription; your recording is saved and will send once one is chosen."
      : "No transcription method is set up. Open Settings > Transcription and choose one.";

  // The upstream speech-to-text provider took too long to respond.
  if (status === 504 || raw.includes("upstream_timeout") || raw.includes("timed out") || raw.includes("did not respond"))
    return durable
      ? "The transcription service timed out - your recording is saved and will keep trying."
      : "The transcription service timed out. Dictation was not transcribed.";

  // The upstream speech-to-text provider is down / circuit-broken ("temporarily unavailable after
  // repeated failures"). The Gateway wraps the proxy's 503/504 as a 502 whose body carries this code.
  if (status === 503 || raw.includes("upstream_unavailable") || raw.includes("temporarily unavailable"))
    return durable
      ? "The transcription service is temporarily unavailable - your recording is saved and will keep trying."
      : "The transcription service is temporarily unavailable. Dictation was not transcribed.";

  // The transcript was produced but could not be delivered into the session (parked on a prompt or a
  // permission dialog and refusing typed input).
  if (raw.includes("submit to session failed"))
    return durable
      ? "Couldn't deliver your dictation to the session yet - it may be busy or waiting on a prompt. It's saved and will keep trying."
      : "Couldn't deliver your dictation to the session - it may be busy or waiting on a prompt.";

  // Any other server-side transcription fault - the provider itself returned an error ("openai
  // transcription failed" / upstream_error), an empty assembly, some other 5xx. A real backend problem,
  // not the user's audio: say so plainly instead of dumping the raw server response.
  return durable
    ? "The transcription service had a problem - your recording is saved and will keep trying."
    : "The transcription service had a problem and couldn't process your recording. Dictation was not transcribed.";
}

function extForMime(mime: string | undefined): string {
  const m = (mime ?? "").toLowerCase();
  if (m.includes("webm")) return "webm";
  if (m.includes("ogg")) return "ogg";
  if (m.includes("mp4") || m.includes("m4a") || m.includes("aac")) return "m4a";
  if (m.includes("mpeg") || m.includes("mp3")) return "mp3";
  if (m.includes("wav")) return "wav";
  return "webm";
}

// ===== Wingman Voice mode (issue #850): the mobile hands-free narration loop =====
// The whole backend is already built and proven on the desktop Cockpit voice tab and the native
// phone app (the explain/voice/ready/menu endpoints below). These typed helpers are the mobile
// PWA's same-origin door to them, each carrying the same Bearer the rest of the client uses so the
// Voice screen works with global Gateway auth on or off. The Wingman is READ-ONLY: explain and the
// voice reads never type into the session; only menu-press / sendPrompt reach the agent, through
// the existing single write chokepoint.
//
// These response shapes are returned by the Gateway via Results.Json WITHOUT a [Produces]
// annotation, so they are not in the generated OpenAPI schema; they are read with narrow local
// types for exactly the fields the Voice screen consumes (the same pattern getDirectors uses).

/** Read-only narration of the latest turn (POST /sessions/{sid}/wingman/explain). Also MARKS the
 *  session as a voice session, so the Gateway's turn-end watcher re-narrates every following turn. */
export interface WingmanExplain {
  reply: string;
  spoken: string;
  replySeconds: number;
  /** True for a fresh/text-only session with nothing to summarize yet (no audio was produced). */
  nothingYet: boolean;
}

/** The precomputed spoken summary + readiness metadata for a session (GET .../wingman/voice). */
export interface WingmanVoice {
  ready: boolean;
  spoken: string;
  reply: string;
  /** ISO-8601 stamp of when this clip was generated; it is the clip's identity (a new turn -> a
   *  new stamp), so the phone uses it to tell a fresh narration from the one it already holds. */
  generatedAt: string;
}

/** One option of a waiting on-screen choice (GET .../wingman/menu). */
export interface WingmanMenuOption {
  /** Short human label, e.g. "1. Yes". */
  key: string;
  /** The exact keystrokes that pick this option. For a single-select menu this includes the
   *  confirm (e.g. "1\r"); for a multiple-select checklist it is just the toggle (e.g. "1"). */
  send: string;
  /** The consequence/risk of choosing this option (<= 18 words). */
  note: string;
  /** True on at most one option - the Wingman's recommended/default pick. */
  recommended: boolean;
}

/** A detected waiting choice and its options (GET .../wingman/menu). */
export interface WingmanMenu {
  isMenu: boolean;
  question: string;
  spoken: string;
  /** "single" to pick exactly one; "multiple" for a pick-any checklist completed by submit. */
  selectionMode: "single" | "multiple";
  /** The keystroke that completes a multiple-select menu (e.g. "\r"); empty for single-select. */
  submit: string;
  options: WingmanMenuOption[];
}

// POST /sessions/{sid}/wingman/explain - mark the session as a voice session AND read its latest
// turn back as a spoken summary, without sending anything into the session. This is what entering
// voice mode fires; the Gateway caches the spoken text + audio so the phone can then download it.
export async function markVoiceAndExplain(sessionId: string, signal?: AbortSignal): Promise<WingmanExplain> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/explain`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    // Switching a session to voice mode ran into out-of-credits (issue #942): the shared notice.
    if (res.status === 402) throw creditsErrorFrom(await res.json().catch(() => ({})));
    throw new GatewayError(res.status, `POST wingman/explain failed: ${res.status}`);
  }
  const body = (await res.json()) as Partial<WingmanExplain>;
  return {
    reply: body.reply ?? "",
    spoken: body.spoken ?? "",
    replySeconds: Number(body.replySeconds ?? 0),
    nothingYet: Boolean(body.nothingYet),
  };
}

// GET /sessions/{sid}/wingman/voice - the precomputed spoken summary + readiness for the session's
// current (latest) narration. ready=false means the Gateway has nothing cached yet.
export async function getWingmanVoice(sessionId: string, signal?: AbortSignal): Promise<WingmanVoice> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/voice`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET wingman/voice failed: ${res.status}`);
  }
  const body = (await res.json()) as Partial<WingmanVoice>;
  return {
    ready: Boolean(body.ready),
    spoken: body.spoken ?? "",
    reply: body.reply ?? "",
    generatedAt: body.generatedAt ?? "",
  };
}

// GET /sessions/{sid}/wingman/voice/audio - the cached MP3 bytes for the session's current clip.
// Returned as an ArrayBuffer so the phone-side download gate (voice/clips.ts) can store it locally
// and expose a "phone-ready" state distinct from "gateway-ready". Binary, never base64 over the wire.
export async function fetchWingmanVoiceAudio(sessionId: string, signal?: AbortSignal): Promise<ArrayBuffer> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/voice/audio`, {
    method: "GET",
    headers: { Accept: "audio/mpeg", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    // Narration audio unavailable because of credits (issue #942): a 402 body is JSON even here.
    if (res.status === 402) throw creditsErrorFrom(await res.json().catch(() => ({})));
    throw new GatewayError(res.status, `GET wingman/voice/audio failed: ${res.status}`);
  }
  return res.arrayBuffer();
}

// GET /sessions/{sid}/wingman/menu - is the agent showing an on-screen menu right now, and what are
// its options? The Voice screen reads this to render pressable option buttons. The Gateway returns
// isMenu=false cheaply (no model call) when the terminal does not look like a menu.
export async function getWingmanMenu(sessionId: string, signal?: AbortSignal): Promise<WingmanMenu> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/menu`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET wingman/menu failed: ${res.status}`);
  }
  const body = (await res.json()) as Partial<WingmanMenu> & { options?: Partial<WingmanMenuOption>[] };
  return {
    isMenu: Boolean(body.isMenu),
    question: body.question ?? "",
    spoken: body.spoken ?? "",
    selectionMode: body.selectionMode === "multiple" ? "multiple" : "single",
    submit: body.submit ?? "",
    options: (body.options ?? []).map((o) => ({
      key: o.key ?? "",
      send: o.send ?? "",
      note: o.note ?? "",
      recommended: Boolean(o.recommended),
    })),
  };
}

// POST /sessions/{sid}/wingman/menu-press - answer a waiting choice from the phone by sending the
// exact keystrokes. This is the single write chokepoint for a choice (the Wingman charter stays
// read-only). For a single-select menu, `send` is one option's full keystroke and `submit` is
// omitted; for a multiple-select checklist, `send` is the concatenated toggle keystrokes of every
// chosen option and `submit` completes the selection.
export async function pressWingmanMenu(
  sessionId: string,
  send: string,
  submit?: string,
  signal?: AbortSignal,
): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const body: { send: string; submit?: string } = submit ? { send, submit } : { send };
  const res = await fetch(`/sessions/${sid}/wingman/menu-press`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST wingman/menu-press failed: ${res.status}`);
  }
}

// POST /sessions/{sid}/voice-mode { enabled } - the owning Director's authoritative voice flag. This
// is the SAME endpoint the native phone app drives (DirectorVoiceClient.SetVoiceModeAsync): enabled
// sets the session's mobile view mode to Voice, so SessionDto.VoiceMode flips true for every client
// (the roster shows it as a voice session and it persists across navigation); disabled leaves voice
// (view mode -> Text). It reaches the Director through the Gateway catch-all session proxy with the
// injected Bearer, exactly like sendPrompt/holdSession. Switching voice on calls this AND
// markVoiceAndExplain (which marks the Gateway's turn-end re-narration set and reads the first turn).
export async function setVoiceMode(sessionId: string, enabled: boolean, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/voice-mode`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ enabled }),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST voice-mode failed: ${res.status}`);
  }
}

// POST /sessions/{sid}/wingman/voice/stop - tell the Gateway to stop keeping voice for this session
// (issue #859). It unmarks the session as a voice session, so the Gateway stops spending the
// per-turn Opus translation + text-to-speech on it (the turn-end watcher and the background sweep
// both skip it once unmarked) and drops its cached clip. The counterpart to markVoiceAndExplain
// (which marks it on entry). "Turn voice off" calls this together with setVoiceMode(sid, false): the
// Director call flips the roster flag, this call stops the Gateway work. Gateway-side and read-only -
// it sends nothing into the session.
export async function stopWingmanVoice(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/voice/stop`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST wingman/voice/stop failed: ${res.status}`);
  }
}
